BitBoxSwiss/bitbox02-firmware

- src/apps/eth/eth.h
- src/apps/eth/eth_common.c
> eth: smaller hex buffer

- src/apps/btc/btc_common.c
- src/apps/btc/btc_common.h
- src/apps/btc/btc_sign.c
- src/ui/components/confirm_transaction.c
- src/ui/components/confirm_transaction.h
- src/workflow/verify_recipient.c
- src/workflow/verify_recipient.h
- src/workflow/verify_total.c
- src/workflow/verify_total.h
- test/unit-test/test_app_btc_common.c
- test/unit-test/test_btc_sign.c
It makes it easier to tack on a separate unit for the total and the fee.
> workflow/verify: combine amount and unit

- src/touch/gestures.c
We are not interrupting this function anywhere, and the locking causes
linting issues.
> gestures: remove unneeded lock

- src/keystore.c
- src/keystore.h
- src/workflow/restore.c
- src/workflow/unlock.c
- test/unit-test/CMakeLists.txt
- test/unit-test/framework/mock_memory.c
- test/unit-test/test_keystore.c
Be able to use it as a PW check only.
> keystore: unit test and harden unlock()

- src/keystore.c
- src/keystore.h
- test/unit-test/test_keystore.c
Will be used to auto-lock the device.
> keystore: add keystore_lock()

- .ci/ci
- .ci/travis-ci
- .gitignore
- Dockerfile
- py/bitbox02/Makefile
- py/bitbox02/__init__.py
- py/bitbox02/bitbox02.py
- py/bitbox02/bootloader.py
- py/bitbox02/devices.py
- py/bitbox02/usb.py
- py/load_firmware.py
- py/requirements.txt
- py/send_message.py
> py: fix typing issues and enforce mypy

- src/drivers/usb/class/hid/hid.c
- src/drivers/usb/class/hid/hid.h
- src/drivers/usb/class/hid/hww/hid_hww.c
- src/drivers/usb/class/hid/u2f/hid_u2f.c
- src/queue.c
- src/queue.h
- test/unit-test/CMakeLists.txt
- test/unit-test/framework/mock_hidapi.c
- test/unit-test/framework/mock_securechip.c
- test/unit-test/test_u2f_hid.c
- test/unit-test/test_u2f_standard.c
- test/unit-test/u2f/ecc.c
- test/unit-test/u2f/u2f_util_t.c
This PR hooks up the `hid_read`/`hid_write` to internal functions to simulate a connected device.
> u2f: Enable tests without hardware

- .ci/check-pep8
- .ci/travis-ci
- Dockerfile
- Makefile
- py/bitbox02/requirements.txt
- py/requirements.txt
- scripts/format-python
- scripts/lint-python
tested by rebuilding and then building firmware.
> Dockerfile: A few more deps

- releases/README.md
> releases/README: typo

- src/ui/screen_process.c
Preliminary cleanup of `screen_process.c` to allow for easier refactoring in the next PR
> Minor improvements

- src/CMakeLists.txt
- src/bootloader/startup.c
- src/drivers/driver_init.c
- src/drivers/driver_init.h
- src/drivers/usb/class/hid/hid.c
- src/drivers/usb/class/hid/hid.h
- src/drivers/usb/class/hid/hww/hid_hww.c
- src/drivers/usb/class/hid/hww/hid_hww.h
- src/drivers/usb/class/hid/u2f/hid_u2f.c
- src/drivers/usb/class/hid/u2f/hid_u2f.h
- src/drivers/usb/class/usb_desc.h
- src/firmware.c
- src/peripherals_init.c
- src/peripherals_init.h
- src/sd_mmc/sd_mmc_start.c
- src/sd_mmc/sd_mmc_start.h
All code changes in preparation for moving some external code out of our `src` dir.
> Prepare for move drivers

- py/bitbox02/u2fhid/u2fhid.py
- py/u2f/bitbox02.py
cid and cmd where mixed up in the u2f python testing script so that didn't work.
> py/u2f: Fix order of cid/cmd and add debug prints

- src/ui/components/trinary_input_char.c
After inserting the first letter into a trinary_input_char,
the following letters would always require backspace to be pressed
twice in order to be effective, even in the case in which one was
in the main screen (i.e. not selecting a sub-alphabet).
This was due to the code setting the in_progress variable to true
even when a letter had just been selected.
> Fix the behaviour of deletions in trinary_input_char.

- src/platform/bitboxbase/leds.c
- src/platform/bitboxbase/leds.h
Improve the firmware API for turning LEDs on/off in the BitBoxBase.
Depends on https://github.com/digitalbitbox/bitbox02-firmware/pull/184.
> Fix BitBoxBase API for LEDs

- external/CMakeLists.txt
- src/CMakeLists.txt
- src/bitboxbase/bitboxbase.c
- src/bootloader/bootloader.c
- src/bootloader/startup.c
- src/firmware_main_loop.c
- src/queue.c
- src/queue.h
- src/u2f/u2f_packet.c
- src/u2f/u2f_packet.h
- src/usart/usart.c
- src/usart/usart.h
- src/usart/usart_frame.c
- src/usart/usart_frame.h
- src/usart/usart_hww.c
- src/usart/usart_hww.h
- src/usb/usb_frame.c
- src/usb/usb_frame.h
- src/usb/usb_packet.c
- src/usb/usb_packet.h
- src/usb/usb_processing.c
- src/usb/usb_processing.h
- src/workflow/workflow.c
Still to do some cleanup/integration - the `#ifdef BBBASE_HMS_BOARD`s are also to be updated to the "real" ones.
> Add USART stack for the BBBase firmware

- py/bitbox02/bitboxbase/__init__.py
- py/bitbox02/bitboxbase/bitboxbase.py
- py/send_message.py
useful after base-api is merged
> py/bitboxbase: Add a few more commands

- src/ui/components/label.c
- test/device-test/src/test_scroll_menu_2.c
The labels size was incorrectly calculated when updating the label
> ui/components/label: fix center top offset

- src/CMakeLists.txt
- src/u2f.c
- src/u2f/u2f_app.c
- src/u2f/u2f_app.h
- src/usb/usb_processing.c
- src/workflow/async.c
- src/workflow/async.h
- src/workflow/confirm.c
- src/workflow/confirm.h
If user has a browser / OS that is sensitive to timing we inform the
user to refresh the browser. Otherwise it just works.
> u2f: Improve u2f

- src/apps/eth/eth_params.c
- Change Single-Collateral DAI to SAI
- Add Multi-Collateral DAI
- Add USDC
> erc20: add Multi-Collateral DAI and USDC

- py/bitbox02/bitbox02/bitbox02.py
- py/send_message.py
Same as in reboot, catch OSError and stop the send_message loop.
> py: handle reset's reboot

- src/ui/components/label.c
Label will scroll will now stay closer to left and right sides.
> components/label: Reduce scoller margin

- py/send_message.py
It was not actually the master xpub.
> py/send_message: fixup xpub wording

- test/unit-test/test_btc_sign.c
A regression in the sighash algo would not have been caught
previously.
> unit_test/test_btc_sign: test signatures

- src/apps/eth/eth_params.c
- src/apps/eth/eth_params.h
Adds the complete list of tokens listed on etherscan.
You can do `git show --minimal` to see that no tokens disappeared.
edit: took top 500 from coin market cap instead.
> eth: Add more erc20 tokens

- py/send_message.py
- src/apps/eth/eth.c
- src/apps/eth/eth_common.c
- src/apps/eth/eth_common.h
- src/apps/eth/eth_sign.c
- test/unit-test/CMakeLists.txt
- test/unit-test/test_app_eth.c
- test/unit-test/test_app_eth_common.c
- test/unit-test/test_app_eth_sign.c
> eth: Change valid xpub keypath length to 4

- src/commander/commander_btc.c
- src/commander/commander_eth.c
- src/ui/ugui/ugui.c
- src/ui/ugui/ugui.h
- src/workflow/verify_pub.c
- test/device-test/CMakeLists.txt
- test/device-test/src/test_token_pub.c
- test/unit-test/CMakeLists.txt
- test/unit-test/test_ugui.c
This will be needed when we add a lot of tokens to support.
> ugui: Add support for dynamically wrapping title

- src/apps/btc/btc_common.c
- src/apps/btc/btc_common.h
- src/commander/commander_btc.c
Will be reused by multisig account registration.
> apps/btc: move _coin_title to btc_common

- .travis.yml
- Makefile
> CI: Cache external dependencies

- src/workflow/show_mnemonic.c
Fits better between the buttons on the top.
> workflow/show_mnemonic: shorter title

- src/apps/btc/btc_common.c
- src/apps/btc/btc_common.h
- test/unit-test/test_app_btc_common.c
Conforms to m/48'/coin'/account'/2'/change/address.
> apps/btc/common: add is_valid_keypath_address_multisig_p2wsh

- .ci/travis-ci
- README.md
codecov has turned out to be pretty useless.
> CI: Disable codecov

- src/commander/commander_btc.c
snprintf writing too much data would make the target
buffer contain a string with no terminating NULL byte. Check
that this is not happening before proceeding.
> commander_btc: Check the return value of snprintf.

- py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
- src/commander/commander.c
- src/commander/commander.h
- src/hww.c
- src/usb/noise.c
- src/usb/noise.h
- src/util.h
Add a layer of encapsulation to HWW packets, to handle data retransmission and arbitration (HWW_REQ_NEW, HWW_REQ_RETRY, HWW_REQ_CANCEL).
> Add hww arbitration layer

- py/bitbox02/bitbox02/bitbox02/__init__.py
> Py: Bump Library Version to 2.0.0

- src/workflow/get_mnemonic_passphrase.c
> workflow/get_mnemonic_passphrase: make visual confirmation scrollable

- src/ui/graphics/graphics.h
- src/ui/graphics/lock_animation.c
- src/ui/graphics/lock_animation.h
- src/workflow/unlock_bip39.c
- src/workflow/unlock_bip39.h
Decouple from workflow, so it can be used in Rust.
> ui: move unlock animation to ui/grpahics/lock_animation

- src/CMakeLists.txt
- src/hww.c
- src/hww_api.c
- src/hww_api.h
Separate the files a bitm so hww.c is doing arbitration (HWW_REQ_*
level) and hww_api.c is doing the actual api processing.
> hww: move actual api processing to new file

- src/rust/bitbox02-rust/src/hww/mod.rs
Used the wrong error code when porting to Rust.
> rust/hww: fix unlock err code

- src/firmware.c
- src/workflow/blocking.c
- src/workflow/orientation_screen.c
- src/workflow/orientation_screen.h
No need for async workflow, it is blocking anyway and usb is activated
only after.
> workflow: simplify orientation screen

- CMakeLists.txt
- test/unit-test/test_restore.c
> CMakeLists: bump version to v9.1.0

- src/rust/bitbox02-rust/src/async_usb.rs
Currently, USB_TASK_STATE, the main executor state, is borrowed for
the whole duration of `spin()`, which includes the polling/execution
of the current task.
This prevents the state to be borrowed again during the execution of a
task. In a normal async runtime, there are things like `spawn(task)`
etc. that need to borrow and modify the executor state though.
The normal way to achieve that is to pop the task from the executor
state (often a task queue), poll it, and put it back in if it is not
finished yet. We do the same, but we have an enum with at most one
task instead of a task queue, so popping just means removing the task
from the enum.
Motivation: in a future PR we plan to add a `next_request()` to the
executor, which can be called from the currently running task. This
future will …
> rust/async_usb: do not borrow executor state during poll

- src/ui/components/trinary_input_string.c
- src/workflow/restore_from_mnemonic.c
Closes https://github.com/digitalbitbox/bitbox02-firmware/issues/578
> Autocomplete

- src/apps/btc/btc_sign.c
First part was in https://github.com/digitalbitbox/bitbox02-firmware/pull/587.
> Signing progress bar / part 2

- src/ui/components/confirm_mnemonic.c
- src/ui/components/confirm_mnemonic.h
- src/ui/components/menu.c
- src/ui/components/menu.h
- src/workflow/show_mnemonic.c
- src/workflow/trinary_input.c
- test/device-test/src/test_all_variants_menu.c
- test/device-test/src/test_confirm_bip39.c
- test/device-test/src/test_scroll_menu_2.c
So the component can be wrapped in Rust.
> components/menu: add param to each callback

- src/u2f/u2f_app.c
so with U2F the bitbox displays this kinda long, hard to recognize or compare half-SHA256 hash in hex for sites that are not listed, it might be easier to recognize sites when using a mnemonic, similar to what happens on a keepkey when using U2F, in fact since the keepkey's implementation is so simple (convert first 44 bits to words using the BIP39 list and that's literally it) I went with the same approach.
Despite the Idea being 100% taken from the nice people at keepkey, the code is 100% hacked together by me using other code that was already in the bitbox firmware and a few extra changes.
1) known sites work as before
2) unknown sites get their half AppID-hash replaced by the 4 BIP-39 words represented by the first 44 bits of that hash (a bit less secure but far more recognizable and …
> Mnemonic U2F

- py/send_message.py
- src/CMakeLists.txt
- src/bootloader/bootloader.c
- src/ui/fonts/arial_fonts.h
Previous commit taken from https://github.com/digitalbitbox/bitbox02-firmware/pull/270
> Hash monospaced, revived

- src/rust/bitbox02/src/util.rs
Builds on https://github.com/digitalbitbox/bitbox02-firmware/pull/635
> unit test and improve FFI str util functions

- src/CMakeLists.txt
- src/apps/btc/btc.c
- src/apps/btc/btc.h
- src/commander/commander.c
- src/rust/bitbox02-rust/src/hww/api.rs
- src/rust/bitbox02-rust/src/hww/api/electrum.rs
- src/rust/bitbox02/src/keystore.rs
- src/rust/bitbox02/src/keystore_stub.rs
- src/rust/bitbox02/src/testing.rs
- test/unit-test/test_app_btc.c
Builds on https://github.com/digitalbitbox/bitbox02-firmware/pull/626
> api: port ElectrumEncryptionKey to Rust

- src/apps/btc/btc.c
- src/apps/btc/btc.h
- src/apps/btc/btc_common.c
- src/apps/btc/btc_common.h
- src/apps/btc/btc_params.c
- src/commander/commander_btc.c
- src/rust/bitbox02-rust-c/src/app_bitcoin.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/params.rs
- test/unit-test/CMakeLists.txt
- test/unit-test/test_app_btc.c
Builds on https://github.com/digitalbitbox/bitbox02-firmware/pull/684
> Port BTC xpub to Rust

- py/bitbox02/bitbox02/bitbox02/__init__.py
Activate the antiklepto protocol in btc_sign().
> py/bitbox02: bump version to 5.2.0

- src/CMakeLists.txt
- src/apps/eth/eth_sighash.c
- src/apps/eth/eth_sighash.h
- src/apps/eth/eth_sign.c
- src/rust/bitbox02-sys/wrapper.h
- src/rust/bitbox02/src/app_eth.rs
- test/unit-test/test_app_eth_sighash.c
To be called when signing an ETH transaction.
> apps/eth/sighash: wrap in Rust 

- CHANGELOG.md
- src/apps/eth/eth_params.c
Contract address: 0x1f9840a85d5af5bf1d1762f925bdaddc4201f984
> apps/eth/params: add uniswap erc20 token

- src/rust/bitbox02-rust/src/hww/noise.rs
BitBoxBase was removed as a target.
> noise: remove stale BitBoxBase comment

- src/common_main.c
- src/memory/memory.c
- src/memory/memory.h
- src/securechip/securechip.c
- src/securechip/securechip.h
- test/unit-test/test_memory.c
And add missing `static` qualifier in memory.c.
> memory,securechip: make setup param const

- .dockerignore
Don't send files to the docker daemon that aren't used in the docker
builds.
> docker: spsed up docker build

- releases/describe_signed_firmware.py
As per the releases/README, the file is supposed to be easy to
audit. Pulling in a dependency makes audit more difficult. It also
makes the script harder to use, if the user does not have the
dependency installed.
This commit inlines the relevant parse_signed_firmware() function from
bootloader.py.
> releases/describe_firmware: remove bitbox02 dependency

- CHANGELOG.md
Added in commit 44a393e027dbea074d866cdefdb4920f7174b856.
> CHANGELOG: Ethereum: add 807 ERC-20 tokens

- src/rust/bitbox02-rust/src/hww/api/bitcoin/signmsg.rs
We disable message signing for taproot addresses for now.
> api/bitcoin/signmsg: disable for taproot

- src/rust/bitbox02-rust/src/hww/api/ethereum/sign_typed_msg.rs
As typed data is streamed from the host, the total number of
confirmation pages is unknown upfront. We do know however the number
of members in the top level struct. We show the current step and total
for the top level struct, but for any given step, there can be lots of
confirmation pages if the member another struct or array.
> eth/signtypedmsg: show progress in title

- CHANGELOG.md
- CMakeLists.txt
- src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
See comment in code for details.
> bitcoin/signtx: allow arbitrary sequence numbers

- src/sd.c
Dead code is a maintenance burden.
> sd: remove dead code

- src/rust/bitbox02-rust/src/hww/api/backup.rs
Check the decoded name. This is a quick sanity check that strings
encoded by nanopb in C can be decoded correctly.
> backup: extend fixture test

- src/CMakeLists.txt
- src/apps/btc/btc.c
- src/apps/btc/btc.h
- src/commander/commander_btc.c
- src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
- src/rust/bitbox02/src/memory.rs
The hash unit tests were ported from test_app_btc_common.c.
> bitcoin: port IsScriptConfigRegistered API call to Rust

- .ci/check-style
- .ci/check-tidy
- .ci/run-container-ci
- CMakeLists.txt
- Dockerfile
List of the updates:
- Ubuntu from 18.04 to 22.04
- gcc from gcc-8 to gcc-10
- clang-* from 8 to 15
> docker: update docker container

- src/keystore.c
Before we used a shared helper function that computes the bip86 keypair for both getting the pubkey as well as signing, as the priv/pubkeys get tweaked with the same tweak.
We might want to implement xpub caching to not re-derive xpubs from the seed more than needed (e.g. when loading many inputs in a BTC transaction), in which case we must be able to derive the bip86 pubkey from an xpub alone, not from an xprv.
> keystore: derive bip86 pubkey from xpub, not from xprv

- src/rust/bitbox02-rust/src/bip32.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
- src/rust/bitbox02-rust/src/hww/api/electrum.rs
- src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
- src/rust/bitbox02-rust/src/keystore.rs
More ergonomic and Rust-like to have a struct with related methods on it.
> rust/bip32: collect methods into a new Xpub struct

- src/rust/bitbox02/src/keystore.rs
In `copy_seed()`, the seed is put on the heap in a Zeroize<> Vec. When creating that vector, if the compiler does not optimize, the seed is first in a stack var and then copied to the heap.
The expression `seed[..seed_len].to_vec()` does not make it obvious that the seed is not stored in an intermediate non-zeroed location before being copied into a Vec.
Instead, we use a zeroized Vec from the start, which eliminates these two potential problems.
Truncating the vector should not result in a copy:
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.truncate
> Note that this method has no effect on the allocated capacity of the vector.
> rust/keystore: more code clarity in memory zeroing

- src/keystore.c
Currently the seed is in RAM in plaintext after unlock. We want to encrypt it instead, using the secure chip.
This refactors the _get_seed and _get_bip39_seed functions to not simply return the static pointer, but a copy, allowing us to perform decryption later once the seeds are encrypted in RAM.
> keystore: copy instead of returning static pointer

- .ci/check-tidy
- src/ui/components/sdcard.c
- src/ui/components/ui_images.c
- Check icon button moved to the top, where it is usually placed
- Vertically mirrored the sd card icon on flipped display, to guide the user using the correct orientation when inserting the physical card.
> ui/components: improve insert SD to continue message

- CHANGELOG.md
- CMakeLists.txt
- src/keystore.c
- src/keystore.h
- src/rust/bitbox02-rust/src/hww/api/backup.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
- test/unit-test/test_keystore.c
- test/unit-test/test_keystore_functional.c
Related: https://github.com/digitalbitbox/bitbox02-firmware/pull/1057
> keystore: encrypt seed in RAM

- src/apps/eth/eth_params.c
By user request.
https://www.reddit.com/r/BitBoxWallet/comments/13kz10s/couple_of_questions/jkp6tf6/?context=3
> apps/eth: add rETH ERC20-token

- src/apps/eth/eth_params.c
> apps/eth: add BOB ERC20-token

- src/apps/eth/eth_params.c
> eth: add GUNTHY ERC20-token

- CHANGELOG.md
- CMakeLists.txt
- py/bitbox02/CHANGELOG.md
- py/bitbox02/bitbox02/bitbox02/bitbox02.py
- src/rust/bitbox02-rust/Cargo.toml
- src/rust/bitbox02-rust/src/hww/api/bip85.rs
Generate and display/verify BIP-85 deterministic child seeds.
> api: add BIP-85 (BIP39 child seeds)

- scripts/reset-version.jlink
It allows to reset firmware and signing keys version.
> scripts: add reset-version.jlink

- .ci/ci
- test/simulator/CMakeLists.txt
> .ci: also build simulator

- src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/policies.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/registration.rs
- src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
> Policies improvements

- Makefile
- scripts/dockerenv.sh
I didn't test this on linux yet.
> Some changes to docker to make it work on apple m1 / macos

- scripts/dockerenv.sh
This commit adds the ability to specify docker container version with CONTAINER_VERSION. E.g:
```
$ CONTAINER_VERSION=40 make dockerdev
```
> Allow specifying a docker image version

- .ci/ci
- py/Makefile
- src/CMakeLists.txt
- test/simulator/CMakeLists.txt
- test/unit-test/CMakeLists.txt
> Remove unused include directory

- src/CMakeLists.txt
- src/rust/bitbox02-sys/build.rs
- src/rust/bitbox02-sys/src/lib.rs
Various improvements, see commit msgs
> Generate rust bindings in rust build scripts

- CHANGELOG.md
- src/rust/bitbox02-rust/src/hww/api/ethereum/params.rs
- src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
- src/rust/bitbox02-rust/src/hww/api/ethereum/sighash.rs
- src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs
- src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs
Goerli testnet shut down April 2020.
> ethereum: remove Goerli testnet

- Makefile
On macos jlink pops up a gui while flashing. Very annoying.
> Makefile: Disable jlink gui in shortcuts

- src/hardfault.c
to make it more comprehensible.
> Update hard fault message

- test/simulator/simulator.c
printf is not async-signal safe, see
https://docs.oracle.com/cd/E19455-01/806-5257/gen-26/index.html
> simulator: async-signal safety

- src/rust/bitbox02-rust/src/hww/api/cardano/address.rs
Coded by ChatGPT o1. Reduces binary size by 2760 bytes.
> cardano: use custom cbor decoder to save binary space

- CHANGELOG.md
- CMakeLists.txt
- py/bitbox02/bitbox02/bitbox02/bitbox02.py
- py/send_message.py
- src/rust/bitbox02-rust/src/hww/api/bitcoin/signmsg.rs
> bitcoin: enable message signing on testnet and regtest

- src/optiga/optiga.c
u2f_counter_inc (return type bool) incorrectly returned 0 (false) for success.
> optiga: u2f_counter_inc return true for success

- src/optiga/optiga.c
It causes a long delay before the orientation animation. It's a sanity
check only, so doing it as part of the factory setup only suffices.
We also enable it in debug builds, so it catches a misconfigured
device (e.g. if you forgot to run factorysetup on a new PCB).
> optiga: move config sanity check to factorysetup only

- src/rust/Cargo.lock
- src/rust/Cargo.toml
- src/rust/bitbox02-rust-c/Cargo.toml
- src/rust/bitbox02-rust/Cargo.toml
https://github.com/RustCrypto/hashes/issues/561 mentioned the no_unroll feature which I wasn't aware of until then.
> Small keccak

- external/asf4-drivers/sd_mmc/sd_mmc.c
- src/sd.c
1 ms is not enough always.
Also add some helpful debug messages
> sd: wait more after reset

- src/CMakeLists.txt
- src/communication_mode.c
- src/communication_mode.h
- src/firmware_main_loop.c
- src/rust/bitbox02-sys/build.rs
- src/rust/bitbox02-sys/wrapper.h
- src/rust/bitbox02/src/lib.rs
- test/simulator/CMakeLists.txt
- test/unit-test/CMakeLists.txt
Bluetooth upgrade will need to know whether to reset the BLE chip based on this.
> add communication_mode_is_ble() and expose to Rust

- src/reset.c
- src/reset.h
- src/rust/bitbox02-rust/src/async_usb.rs
- src/rust/bitbox02-rust/src/hww/api/bluetooth.rs
- src/rust/bitbox02-sys/build.rs
- src/rust/bitbox02/src/lib.rs
Paired with https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/3323
> Reset after upgrade

- src/memory/spi_mem.c
This adds a read back of the written page data to check that the writing completed successfully.
> memory/spi_mem: add read check after write/erase

- src/da14531/da14531.c
There is no overflow as the device name and product strings are smaller than these buffers, but it's good to add checks anyway in case that should change.
> da14531: add buffer bound checks

- src/memory/memory.c
No caller ran into this, but good to make sure.
> memory: add a check to avoid overflow

- src/keystore.c
- src/keystore.h
- src/rust/bitbox02-rust/src/workflow/mnemonic.rs
- src/rust/bitbox02/src/keystore.rs
- src/rust/bitbox02/src/ui/types.rs
- src/ui/components/trinary_input_string.c
- src/ui/components/trinary_input_string.h
This PR is a prep PR for https://github.com/BitBoxSwiss/bitbox02-firmware/pull/1540
> Wordlist refactor

- src/ui/components/button.c
- src/ui/components/confirm_gesture.c
- src/ui/components/icon_button.c
- src/ui/components/keyboard_switch.c
- src/ui/components/label.c
- src/ui/components/left_arrow.c
- src/ui/components/right_arrow.c
- src/ui/components/trinary_input_char.c
- src/ui/event.h
In rust later I prefer to use const instead of mut pointers where possible
> gestures: constify const value

- test/hardware-fakes/src/fake_memory.c
Don't know why CI didn't catch it before.
> test: apply clang-format
