BitBoxSwiss/bitbox02-firmware

external/CMakeLists.txt

Pulled in libwally and rebased our patches, and put them into the
bitbox02-firmare branch of
https://github.com/shiftdevices/libwally-core (reviously firmware_v2
branch).

CMakeLists: update libwally (and secp256k1)

---

src/util.h
test/unit-test/CMakeLists.txt
test/unit-test/test_util.c

This stops double evaluation of arguments to min/max. With previous macro, `MIN(i++,16)` would have increased `i` twice.

src/util: Improve min/max

---

src/ui/components/confirm_transaction.c

To not overlap with confirmation arrows.

workflow/verify: reformat

---

src/ui/components/insert_sd_card.c
src/ui/components/remove_sd_card.c

Instead of an empty screen containing the button.

components/insert_sd_card: use button directly

---

src/reset.c

While the keystore could not be used after resetting, we assume a
locked keystore when starting out creating a new one.

reset: lock keystore

---

bootloader.ld
firmware.ld
src/CMakeLists.txt
src/bootloader/bootloader.c
src/bootloader/startup.c
src/drivers/usb/class/hid/hww/hid_hww.c
src/drivers/usb/class/hid/u2f/hid_u2f.c
src/factorysetup.c
src/hww.c
src/queue.c
src/queue.h
src/u2f.c
src/u2f/u2f_packet.c
src/u2f/u2f_packet.h
src/ui/screen_process.c
src/usb/usb.c
src/usb/usb_frame.c
src/usb/usb_frame.h
src/usb/usb_packet.c
src/usb/usb_packet.h
src/usb/usb_processing.c
src/usb/usb_processing.h
test/device-test/src/framework/test_common.c
test/device-test/src/test_usb_cmd_process.c
test/unit-test/CMakeLists.txt
test/unit-test/framework/mock_hidapi.c

Fix issues with U2F and HWW functionality stepping on each others toes.
To test/build either wipe `/build` or run `cmake -DHEAP_SIZE=0x18000`. The value in the build directory is cached and will not change, even though it changed in the cmake files.

U2F Separation

---

CMakeLists.txt
Makefile
arm.cmake
external/CMakeLists.txt
scripts/CMakeLists.txt
scripts/bootloader.jlink
scripts/firmware.jlink
scripts/jlink-gdb-debug/.gdbinit
scripts/jlink-gdb-debug/README.md
src/CMakeLists.txt
src/drivers/SAMD51_DFP/1.0.70/gcc/gcc/startup_samd51.c
src/drivers/driver_init.c
src/drivers/hal/utils/src/utils_syscalls.c
src/drivers/usb/class/hid/hww/hid_hww.h
src/hardfault.c
src/util.h
test/device-test/CMakeLists.txt
test/device-test/src/framework/test_common.c
test/device-test/src/test_trace.c

This PR introduces two things:
The detailed instructions are in `/scripts/jlink-gdb-debug/README.md`. Essentially this allows you to add regular `printf`s and they are printed on a screen on the computer running the GDB Server.
Semihosting also allows us to open files and dump binary data with normal `fopen`/`fwrite` libc functions.
`printf` uses a function called `_write` to actually write the resulting bytes. This PR implements it by printing the bytes to the screen. The default implementation of `_write` is a no-op and does nothing. 
`trace` is a macro that expands to printf in a semihosted build and expands to no-op in a non-semihosted build. This allows us to leave some debugging functionality in the firmware and reduce the churn while implementing new features.
You can test it with …

Create tracing/logging framework.

---

src/u2f.c
src/u2f/u2f_app.c
src/u2f/u2f_app.h

with our current firmware architecture and the fact that windows
requires a response within 2-3s we need to reduce the time for the user
to respond to less than 1s.
This timeout was empirically found using windows 1903.

u2f: reduce time to response

---

.ci/ci
Makefile
src/CMakeLists.txt

Locks the dev bootloader so it can't be erased.

CMakeLists: new target, bootloader-development-locked

---

src/CMakeLists.txt
src/firmware.c
src/firmware_main_loop.c
src/firmware_main_loop.h
src/u2f/u2f_app.c
src/ui/screen_process.c
src/ui/screen_process.h
src/workflow/blocking.c
test/device-test/src/test_all_variants_menu.c
test/device-test/src/test_bip39.c
test/device-test/src/test_button_tap.c
test/device-test/src/test_confirm_bip39.c
test/device-test/src/test_entry_screen.c
test/device-test/src/test_scroll_menu.c
test/device-test/src/test_scroll_menu_2.c
test/device-test/src/test_simple_slide.c
test/device-test/src/test_slide_info.c
test/device-test/src/test_tap_menu.c
test/unit-test/CMakeLists.txt
test/unit-test/test_workflow_blocking.c

Moved the usb processing and is_done() logic outside of `_screen_process()`.
Only the main loop should be responsible for calling the USB handlers - does this have anything to do with the GUI after all? Same for the workflow-related logic (blocking, timeouts, etc).
Note that this is just code wrangling so the new implementation should be 100% equivalent to the current one - if it isn't, that's a bug.
Depends on #147.

Separate screen-, workflow- and usb-related functions

---

src/firmware.c
src/workflow/workflow.c
src/workflow/workflow.h

`workflow_change_state` was supposed to be "switching workflows based on
user inputs" (as per the docs), but in practice all what it was doing was switching to
the "Tap this side" screen.

workflow.c: Remove the useless "workflow_change_state" function.

---

src/ui/components/trinary_input_char.c
src/ui/components/trinary_input_char.h
src/ui/components/trinary_input_string.c

The parent component (trinary_input_string) takes care of handling the
alphabet. It was awkward for it to be done twice, once with an
arbitrary horizontal space.

ui/components/trinary_input_char: remove redundant set_alphabet

---

external/CMakeLists.txt
src/keystore.c

- new branch
https://github.com/shiftdevices/libwally-core/tree/bitbox02-firmware-20191011,
which is based on
https://github.com/ElementsProject/libwally-core/commit/ff01f0749006161e25363234bcf9bad7da60f985
- the bundled sep256k1 is replaced with
https://github.com/digitalbitbox/secp256k1-zkp/tree/bitbox02-20191013,
which is based on
https://github.com/ElementsProject/secp256k1-zkp/commit/85bcb7c951ed697acc4560a7e857b06cc7790618,
with cherry-picked
https://github.com/bitcoin-core/secp256k1/pull/337/commits/dcb2e3b3fff0b287d576842aabe5c79f2fe4df30
Deleted the build related custom wally commits, as we can configure it
from our own CMakeLists.txt. The big commit is replaced with the above
cherry picked upstream commit and configured with --with-ecmult-gen-precision=2.

external: update libwally-core, clean up secp256k1

---

releases/README.md
releases/describe_signed_firmware.py
scripts/lint-python

The current instructions tell you how to reproduce the unsigned
firmware.  This adds a script to dump info about the signed release,
so the user can verify that the unsigned firmware is part of the
signed firmware binary.
It also dumps the hash which should match the hash shown by the
bootloader before booting the firmware.

releases: add script to verify a signed releases

---

src/u2f/u2f_packet.c
src/u2f/u2f_packet.h
src/usb/class/hid/hww/hid_hww.c
src/usb/class/hid/u2f/hid_u2f.c
src/usb/usb_packet.c
src/usb/usb_packet.h
src/usb/usb_processing.c
test/unit-test/framework/mock_hidapi.c

Remove the assumption spread throughout hid_hww.c, hid_u2f.c, and
usb_processing.c, that sends should start only after a receive and
receives should start only when a frame has been sent.
Split the single code flow performing the send->rcv->send->rcv... operations
into two separate call stacks. The read part will reissue a (async) read
as soon as data arrives and finished processing. The write part will
continuously issue (async) sends until the write buffer is flushed
completely. Whenever somebody queues new data to write, a new series of
sends will start.

usb/hid: Separate the code sending and receiving packets.

---

external/asf4-drivers/qtouch/qtouch.h

Users reported issues with the sensors becoming unresponsive. This was
due to the calibration threshold being set too low which made the
calibration kick in even if the user was present. Increasing this value
makes the device less likely to become unresponsive.

qtouch: Increase calibration threshold

---

src/ui/oled/oled.c
src/ui/oled/oled.h

By configuring the device correctly we don't need to move around bits.

ui/oled/oled: simplify drawing code

---

src/u2f/u2f_packet.c
src/u2f/u2f_packet.h
src/usart/usart_frame.c
src/usart/usart_frame.h
src/usb/usb_packet.c
src/usb/usb_packet.h
src/usb/usb_processing.c

Use the proper format for U2F-over-UART errors:
endpoint == 0xFF, 1 byte payload containing the error code.

U2F-over-USART: format error frames correctly.

---

.ci/travis-ci
py/requirements.txt

Needed for the UART connection to the BitBoxBase HSM.
Dockerfile including this was build and pushed with :8.

py: add pyserial to requirements.txt

---

.ci/travis-ci
py/requirements.txt

Cherry-pick of https://github.com/digitalbitbox/bitbox02-firmware/pull/210 on top of `hsm` to allow for separate HSM development.

py: add pyserial to requirements.txt (cherry-pick for the HSM branch)

---

src/bitboxbase/bitboxbase.c

I must have missed this when merging the qtouch stuff.

bitboxbase: enable qtouch

---

src/bootloader/bootloader.c

Since the logotype changes for different products the "show hash screen"
is now not shoing the logo anymore and is instead showing the hash over
four lines.

bootloader: change how firmware hash is displayed

---

src/bootloader/bootloader.c
src/screen.c
src/screen.h
src/ui/oled/oled.c
src/workflow/reboot.c
src/workflow/workflow.c

Also don't rotate screen in bootloader and always set it to not flipped
when rebooting

bitboxbase: Don't abort on wrong screen orientation

---

src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/lib.rs

optimize for size instead of whatever is default. Also remove some debug strings by abort as the panic strategy instead of unwind.

rust: Change optmimzation for size

---

py/bitbox02/bitbox02/__init__.py
py/send_message.py

I also saw that in https://github.com/digitalbitbox/bitbox02-firmware/blob/master/messages/hww.proto the btc requests are included, but the eth requests are not. What is the reason for that? I also did not understand, why I could not do `bitbox02.eth.ETHPubRequest.Address`, even though `eth` is aliased as an import of `generated.eth_pb2` in the bitbox02 package.

Py: Fix sendmessage eth and btc pubkey pb2 import

---

py/bitbox02/communication/bitbox_api_protocol.py

In case the pairing fails in the BitBox02's init function, the hid handler was never closed. This commit closes it in case of an exception.

Py: Close hid device on pairing failure

---

py/bitbox02/bitboxbase/bitboxbase.py
py/bitbox02/communication/bitbox_api_protocol.py
py/load_firmware.py
py/send_message.py

The noise verification callback might not return if the callback function does a blocking call to a client (for example to render the pairing code on a window). If that is the case, the client would display the pairing code before it is displayed on the device. To evade this, place the callback after making the pairing verification request to the device, and read the response once the callback returns.
Why is the 2ufhid interface used here in the first place? Is this just the unencrypted interface, or is it a separate hid handler?

Py: Move noise verification callback after send, before response

---

messages/btc.proto
py/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/communication/generated/btc_pb2.pyi
src/apps/btc/btc.c
src/apps/btc/btc_common.c
src/commander/commander_btc.c
test/unit-test/test_app_btc.c
test/unit-test/test_app_btc_common.c

BIP49: Testnet uses 0x044a5262 "upub" and 0x044a4e28 "uprv."
BIP84: Testnet uses 0x045f1cf6 "vpub" and 0x045f18bc "vprv."
Update the generated python protobuf code.
Add extra fields to the BTCPubRequest for each of them.

Add testnet segwit upub and vpub

---

py/bitbox02/communication/bitbox_api_protocol.py

Equivalent of https://github.com/digitalbitbox/bitbox02-api-go/pull/18

py/bitbox02: peg attestation pubkey to allowed bootloader hash

---

scripts/docker_exec.sh

Running docker_exec.sh <command> will always exit 0, even if the invoked command has failed. This prevents using it as e.g. a git hook to verify commits.

docker_exec.sh: Fail the docker subprocess returns nonzero.

---

src/CMakeLists.txt

cbindgen was emitting unneccesary warnings. Basically one warning for
every object that it didn't create bindings for.

rust-cbindgen: Quiet

---

py/bitbox02/bitbox02/bitbox02.py
src/apps/btc/btc_sign.c
test/unit-test/test_btc_sign.c

Transaction byte version 2 was introduced with the CHECKSEQUENCEVERIFY soft fork and has been in usage with many clients (including Bitcoin Core as a default) since a long time.
For the sake of transaction uniformity we should change this in the desktop app as well. Electrum for example also uses the version 2 transaction byte since nearly a year now: https://github.com/spesmilo/electrum/pull/5039 and bitcoin since 2014 https://github.com/bitcoin/bitcoin/pull/7562

firmware/btc: Support for transaction byte version 2

---

src/CMakeLists.txt
src/bootloader/bootloader.c
src/bootloader/mpu_regions.c
src/bootloader/mpu_regions.h
src/bootloader/startup.c
src/common_main.c
src/flags.h
src/mpu.c
src/mpu.h
test/device-test/CMakeLists.txt
test/device-test/src/test_mpu.c

The default MPU configuration left by the bootloader disables
pages 2000-2047. This is pointless as it means losing 48 pages
at the end of the NVM main address space to no real benefit.
Extend the APP_DATA_1 MPU region until the end of the flash address
space; the protected bootloader section will remain R/W blocked for
the firmware as it has higher priority in the MPU table.

Enable R/W access to pages 2000-2047 in the MPU.

---

CMakeLists.txt

The reset command now reboots before returning a response, which is a
breaking change.

CMakeLists: bump versions to 5.0.0

---

src/u2f.c
src/u2f/u2f_packet.c
src/usb/usb_packet.c

The U2F hijack mechanism for transmitting data
over U2F sign requests is obsolete, and was never
implemented in the first place. Remove support
for this entirely. The special appIds using the U2F hijack
mechanism will now be treated as all other appIds.

u2f.c: Remove support for U2F hijack.

---

src/ui/components/confirm_gesture.c

During password entry the clamp gesture would get stuck if you started
it near the limit of where it can be started (approximately two thirds
to the right) and then released it on the wrong side (a little bit less
than two thirds).

ui/components/confirm_gesture: Fix clamp getting stuck

---

src/CMakeLists.txt
src/apps/btc/btc_params.c
src/apps/btc/btc_params.h
src/apps/btc/btc_sign.c
src/apps/btc/confirm_locktime_rbf.c
src/apps/btc/confirm_locktime_rbf.h
test/unit-test/CMakeLists.txt
test/unit-test/test_app_btc.c
test/unit-test/test_app_btc_confirm_locktime_rbf.c
test/unit-test/test_btc_sign.c

The following pairs of locktime and sequence bytes are now supported:
locktime = 0 , nsequence = 0xffffffff
-> as before
locktime > 0, nsequence = 0xffffffff - 1
-> nsequence < 0xffffffff indicates a locktime on a transaction.
locktime > 0, nsequence = 0xffffffff - 2
-> nsequence == 0xffffffff - 2 indicates that the transaction is RBF. Since
we have the above rule on the locktime, the RBF rule only makes sense if the locktime is not zero again.
All other combinations of nsequence and locktime bytes are still not allowed. Other combinations should eventually be allowed as well to support BIP68 (nseuqnece byte definitions), BIP65
(OP_CHECKLOCKTIMEVERIFY) and BIP112 (OP_CHECKSEQUENCEVERIFY).
The relaxed constraints were chosen to accommodate for electrum's usage of RBF. The relation between …

firmware: BTC sign, supported locktime and sequence bytes

---

src/apps/btc/btc_sign.c

Less lines, and easier to extend (which we will do when adding more
complicated btc scripts).

apps/btc/btc_sign: copy struct instead of copying each field

---

src/keystore.c
test/unit-test/test_keystore.c

The process of creating a new wallet is:
create seed (status: seeded) -> unlock -> create backup (status:
initialized).
After unlock, before create backup, the device could be unplugged, in
which case the process starts again.
There is an issue though if the process is started again without
reconnecting: the previous seed is still in memory, but a new seed is
created, so unlock runs into the "Seed has suddenly changed" abort.
The abort is a sanity check, but in this case, nothing bad would have
happened otherwise.

keystore: erase seed from memory before creating a new one

---

src/workflow/backup.c

This has one potential blocker. The three confirmation screens have the confirm button on opposite sides. Especially weird when the name is short and the scrollable slider isn't needed.

workflow/backup: Show long names correctly

---

messages/btc.options
messages/btc.proto
py/bitbox02/bitbox02/bitbox02.py
py/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/communication/generated/btc_pb2.pyi
py/send_message.py
src/apps/btc/btc_sign.c
test/unit-test/test_btc_sign.c

It is the derivation to the account, e.g. m/84'/0'/1'.
It is a prefix to all input and change keypaths.
This subsumes bip44_account (as it is part of it), and will make it
easier to verify the account to be used during signing upfront. Doing
it that way is easier to read/maintain, as we don't need to cache the
result so each input/change don't have to redo the validation.

apps/btc/sign: keypath_account added to BTCSigninit

---

messages/btc.proto
py/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/communication/generated/btc_pb2.pyi
src/apps/btc/btc.c
src/apps/btc/btc_common.c
src/commander/commander_btc.c
test/unit-test/test_app_btc.c
test/unit-test/test_app_btc_common.c

Allow retrieval and verification of multisig xpubs. The versions are
taken from Electrum (Zpub for mainnet, Vpub for testnet, for p2wsh
scripts).

apps/btc/common: enable xpub for m/48'/coin'/account'/2', Zpub, Vpub

---

src/ui/ugui/ugui.c

UG_PutChar does a lot of looping and pixel drawing, which is pretty
slow. A longtouch confirm for example is noticable slower if a long
string is rendered, like an xpub (most of it cut off being out of
screen).
With a small bound check the device feels snappier and the
scrolling/confirm speeds are much more consistent.
Vertical check could be added, but we have no vertical scrolling, so
there is no benefit.

ugui: don't draw out of screen horizontally

---

src/apps/btc/btc_bip143.c

Must have been a copy/paste error, ctx can be a stack var instead.

apps/btc/bip143: remove needless "static" keyword

---

src/apps/btc/btc_common.c
src/apps/btc/btc_common.h
test/unit-test/test_app_btc_common.c

Useful for registering and identifying multisig configs on the device.

apps/btc/common: add btc_common_multisig_hash

---

src/rust/bitbox02/src/lib.rs
src/ui/components/confirm.c
src/ui/components/confirm.h
src/ui/components/icon_button.c
src/ui/components/icon_button.h

Quite a few workflow can benefit of a "next" button instead of a
checkmark, when there are multiple consecutive confirmation screens.
This will be used in multisig confirmation.
A horizontal animation is added instead of a vertical one.

components/icon_button: add ICON_BUTTON_NEXT

---

src/apps/btc/btc.c
src/apps/btc/btc_common.c
src/apps/btc/btc_common.h
src/apps/eth/eth.c
test/unit-test/test_app_btc_common.c
test/unit-test/test_apps_common_bip32.c
test/unit-test/test_keystore_functional.c

More and more places are hardcoding the needed xpub version bytes
ad-hoc. Preparation for multisig Zpub use.

apps/btc: move xpub_type to btc_common_encode_xpub

---

src/ui/components/confirm.c
src/ui/components/icon_button.c

The UX was inconsistent.
The buttons are also moved a little closer to the edges to make a bit
more space for titles.

components/confirm: move confirm buttons to top, always.

---

py/bitbox02/bitbox02/bitboxbase/bitboxbase.py
py/bitbox02/bitbox02/communication/__init__.py
py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
py/load_firmware.py
py/send_message.py

Add two arguments to the bitbox02 initialization that allow to pass in a private key and an existing set of static device public keys.

Py: Add possibility to check noise keys

---

CMakeLists.txt

It is easier to use if everytime you run all tests or a specific test,
that the coverage report only shows the result of the last run, and
not the result of all previous runs combined.

unit-test: make a fresh coverage report every time

---

src/CMakeLists.txt
src/apps/btc/btc.c
src/apps/eth/eth_sign_msg.c
src/util/util_string.c
src/util/util_string.h
test/unit-test/CMakeLists.txt
test/unit-test/test_util_string.c

To be able to print names on the screen for confirmation, they need to
be all ascii and not start/end with spaces.
ascii util function added also for bytes as that can be reused in
eth's sign message function.

btc,eth: validate names / ascii

---

src/apps/btc/btc.c
src/apps/btc/btc.h
src/commander/commander.h
src/commander/commander_btc.c

So the client can prompt the user to enter a different name.

apps/btc: pass on DUPLICATE error in account registration

---

src/ui/component.h
src/ui/components/confirm_mnemonic.c
src/ui/components/scroll_through_all_variants.c
src/ui/components/scroll_through_all_variants.h
src/ui/event_handler.c
src/ui/ui_util.c
src/workflow/show_mnemonic.c
test/device-test/src/test_all_variants_menu.c
test/device-test/src/test_scroll_menu_2.c
test/device-test/src/test_simple_slide.c

UI  improvements for scroll_through_all_variants.
Don't show the forward/back arrows of scroll_through_all_variants
when the first or last option is being shown. Also, replace the "Cancel" text with a cross icon.
Still not sure about 9aa605f, hence the WIP.
Edit: 9aa605f got removed, as it's only needed for future work.

Improve scroll list

---

py/bitbox02/bitbox02/bitboxbase/bitboxbase.py
py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
py/bitbox02/bitbox02/util.py
py/load_firmware.py
py/send_message.py

I added optional keys caching in our python tools.
@TheCharlatan I split out the two old callbacks again from the noise config object.

py: Cache keys by default

---

src/queue.c

The queue_pull and queue_clear functions can suffer for a race condition that makes the HWW queue evaluate incorrectly the number of packets available for output. Namely, queue_clear being invoked from interrupt space after queue_pull has read the start point of the queue but before
it's read the end point makes the comparison for an empty queue (`start == end`) lose data.
Add synchronization primitives (from hal_atomic.h) to disable interrupts when queue manipulation is invoked, so that both interrupt code and user code is executed atomically.

queue.c: Add synchronization primitives.

---

py/bitbox02/bitbox02/communication/bitbox_api_protocol.py

Change the various if/else checks on the noise version numbers
to use polymorphism instead. Move all the noise-level operations
to a separate set of classes to sharpen the separation between noise
and application layers.

Python scripts: Cleanup Noise API versioning.

---

CMakeLists.txt
py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
src/usb/noise.c

Add encapsulation to Noise handshake requests and OP_NOISE_MSG responses. This fixes a long standing bug that makes handshakes fail occasionally, and allows errors to be reported in a coherent way on the HWW stack.

Noise encapsulation

---

py/bitbox02/bitbox02/communication/bitbox_api_protocol.py

Minor potential issue in pre-release versions; use self.version after
it is fully initialized.

py: fix max version check

---

py/bitbox02/bitbox02/communication/bitbox_api_protocol.py

We support 6.0.0 and 7.0.0, so failing at min version + 1 does not
work.
Also the min check somehow did the max check, must have been a rebase
error or sth.

py: explicit max upper version

---

src/usb/noise.c

If handshake fails, a OP_I_CAN_HAS_HANDSHAEK == 2 response status is
sent. This is not even recognized by the python code. Remove it
and use OP_STATUS_FAILURE instead.
Depends on #363.

Remove useless noise response code

---

py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
src/hww.c

OP_INFO's purpose is to query the firmware version if it is not
available via the usb descriptor (bitboxbase, bitboxbridge, etc.), so
querying it should work the same way independently of the firmware
version.
Since the HWW framing layer was introduced, the call to OP_INFO needs
to be framed, which breaks the purpose. The fix is to graduate it to
the top level (treated as a special case).
The get_info method is additionally converted to a function (new name;
query_info), as it does not depend on the instance anymore (no use of
self).

hww: graduate op_info to the hww framing layer

---

src/workflow/blocking.c
src/workflow/blocking.h
src/workflow/cancel.c
src/workflow/confirm.c
src/workflow/confirm.h
src/workflow/password_enter.c
src/workflow/restore_from_mnemonic.c
src/workflow/sdcard.c
src/workflow/status.c
src/workflow/unlock.c
src/workflow/verify_recipient.c
src/workflow/verify_total.c
test/unit-test/framework/mock_blocking.c
test/unit-test/test_workflow_blocking.c
test/unit-test/test_workflow_cancel.c
test/unit-test/test_workflow_status.c

The possibility of forcefully unlocking a blocking workflow
is not used anywhere and adds additional complexity to the code.
Get rid of it.

blocking.c: Remove unused workflow_force_unlock() calls.

---

src/apps/eth/eth_sign_msg.c
src/rust/bitbox02-rust-c/src/util.rs
src/util/util_string.c
src/util/util_string.h
test/unit-test/test_util_string.c

rust: simplify CStrMut.AsMut

---

py/bitbox02/bitbox02/communication/bitbox_api_protocol.py

Regression from b698a92fee36708c6e73e54ad1ca35e972c969a7
The unlock call can also return UNINITIALIZED besides FAILURE and
SUCCESS.
```
-                # since 3.0.0, unlock can fail if cancelled
-                if unlock_result == RESPONSE_FAILURE:
-                    self.close()
-                    raise Exception("Unlock process aborted")
...
+        if unlock_result != RESPONSE_SUCCESS:
+            self.close()
+            raise Exception("Unlock process aborted")
+
```

py/bitbox02: fix unlock call on uninitialized device

---

src/hww.c
src/hww.h
src/u2f.c
src/u2f.h
src/u2f/u2f_app.c
src/u2f/u2f_app.h
src/ui/workflow_stack.c
src/ui/workflow_stack.h
src/usb/usb_processing.c
src/usb/usb_processing.h

When the USB stack is waiting for an asynchronous operation
to complete, a timer is started. If no traffic is received by the BB02
within 0.5s, the outstanding operation is forcefully aborted.

USB: Async workflow timeouts.

---

.clang-format

Without this change, some include blocks are merged together
making C code auto-formatting very annoying if not impossible.
See https://clang.llvm.org/docs/ClangFormatStyleOptions.html.

clang-format: preserve include blocks when formatting

---

src/reset.c
src/ui/components/status.c
src/ui/components/status.h
src/workflow/status.c
test/unit-test/test_ui_components.c
test/unit-test/test_workflow_status.c

delay is the same for every invocation, and is unlikely to change.

components/status: remove unused param `delay`

---

src/rust/bitbox02/src/ui.rs
src/ui/components/confirm.c
src/ui/components/confirm.h
src/workflow/confirm.c
src/workflow/workflow.c
test/unit-test/test_ui_components.c

Makes most call sites simpler.

components/confirm: one callback instead of two

---

src/rust/bitbox02/src/ui.rs
src/ui/components/confirm.h
src/ui/components/status.h
src/ui/components/trinary_input_string.c
src/ui/components/trinary_input_string.h

into_raw makes Rust forget about the pointer. A corresponding from_raw
is needed to bring it back and clean it up properly.

rust/bitbox02/ui: properly clean up callbacks

---

src/factorysetup.c

Was a regression; the factorysetup has only minimal status output on
the screen that should not be eliminated.

factorysetup: remove screen processing

---

py/bitbox02/setup.py

The python libraries dependencies now no longer have an upper ceiling. The funcionality of the library was tested with these relaxed requirements with electrum. Comprehensive testing against many other
versions of the dependencies (such as hidapi version 0.9.0) was not done.

Relax the python library requirements

---

.gitignore
py/bitbox02/Makefile
py/bitbox02/bitbox02/bitbox02/__init__.py
py/bitbox02/bitbox02/communication/generated/backup_commands_pb2.py
py/bitbox02/bitbox02/communication/generated/bitbox02_system_pb2.py
py/bitbox02/bitbox02/communication/generated/bitboxbase_pb2.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/bitbox02/communication/generated/common_pb2.py
py/bitbox02/bitbox02/communication/generated/eth_pb2.py
py/bitbox02/bitbox02/communication/generated/hww_pb2.py
py/bitbox02/bitbox02/communication/generated/keystore_pb2.py
py/bitbox02/bitbox02/communication/generated/mnemonic_pb2.py
py/bitbox02/bitbox02/communication/generated/perform_attestation_pb2.py
py/bitbox02/bitbox02/communication/generated/random_number_pb2.py
py/bitbox02/bitbox02/communication/generated/system_pb2.py

Our protobuf definitions have no package specified.
This is intentional. The protos aren't used anywhere except
communications with the device and adding a package namespace makes
type names even longer for too little benefit.
However, the bitbox02 Python package is used elsewhere like the
electrum app where all its py protobufs combined may have name
collisions due to the empty package name.
The generated protos for Go, C and Rust bindings remain as is for now:
package name isn't used on the wire. This is not a breaking change.
Once this is submitted and a new bitbox02 py package is released, this should permanently resolve the issue in https://github.com/spesmilo/electrum/pull/5993#issuecomment-611080550.

py/bitbox02: namespace all protos with package directive

---

py/bitbox02/bitbox02/bitbox02/__init__.py
py/bitbox02/setup.py

See
https://github.com/spesmilo/electrum/pull/5993#issuecomment-611719275:
https://pypi.org/project/typing/
NOTE: in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT.

py/bitbox02: remote typing dependency and bump version

---

src/CMakeLists.txt
src/rust/bitbox02/src/commander.rs
src/rust/bitbox02/src/lib.rs

Same style as [process_packet](https://github.com/digitalbitbox/bitbox02-firmware/blob/6b44ed0e5711218efdd875ac308b01b9ee86258c/src/rust/bitbox02/src/hww.rs#L19), which will be deleted soon.

rust/bitbox02: wrap C commander()

---

.gitmodules

This is no longer used since https://github.com/digitalbitbox/bitbox02-firmware/pull/465

external: remove noise-c submodule

---

py/bitbox02/Makefile

Somehow, Python's protobuf gen fails with:
hww.proto:17:1: Multiple package definitions.
hww.proto:18:1: Multiple package definitions.
hww.proto:19:1: Multiple package definitions.
...
The only place where this could happen seems to be during the copy
where the cp command doesn't actually replace an existing destination.
It could happen if the host OS has some default cp flags set, like -u.
Instead of copying and then sed-updating in-place, do the package
insert in memory and output the result directly to the dest location
This should make it idempotent.

py/bitbox02: avoid "multiple package definitions" proto error

---

Makefile

Created by e.g. `make firmware-semihosting'

Makefile/clean: delete build-semihosting

---

src/rust/bitbox02-rust/src/workflow/unlock.rs

"You will be asked to visually confirm your passphrase now." is better
confirmed with the next arrow than a checkmark.

ui/unlock: show next arrow instead of checkmark to go to visual conf

---

src/u2f/u2f_app.c

'U2f authenticate' is a bit too long, touching the control buttons on
the top.

u2f: change label 'U2F authenticate' -> 'U2F auth'

---

src/CMakeLists.txt
src/apps/btc/btc_sign.c
src/ui/components/empty.c
src/ui/components/empty.h
src/ui/screen_stack.c
src/ui/screen_stack.h

The device waits for the next api call from the client after
confirming an output. During this time, the 'See the BitBoxApp' is
shown as the default screen if there is nothing else on the screen
stack.
This can result in an ugly flicker if there are multiple outputs to
confirm.
This is an attempt to reduce the flicker by just rendering an empty
screen (black screen) instead the regular waiting screen in this case.

apps/btc/sign: replace 'See the BitBoxApp' flicker between outputs

---

src/ui/components/keyboard_switch.c

Part of https://github.com/digitalbitbox/bitbox02-firmware/pull/416. The other PR changed to start with digits, but I kept it to start at `abc`

components/keyboard_switch: show next keyboard, not current

---

src/ui/components/trinary_input_string.c

Part of #416. The other PR accidentally removed the ability to cancel the input (used when restoring from mnemonic). This PR adds a commit that shows a proper cancel button instead.

Password improvements

---

src/ui/components/confirm_gesture.c
src/ui/components/confirm_transaction.c
src/ui/components/icon_button.c
src/ui/components/left_arrow.c
src/ui/components/right_arrow.c
src/ui/components/ui_images.c
src/ui/components/ui_images.h

Part of #416. The other PR did not hollow out the right arrow, used in scrolling through the words when showing the mnemonic.

font-size: use hollow arrow (not filled), and bigger arrows

---

src/ui/components/confirm.c

Fix centering algorithm - before it would center the text in the whole
screen. Now it is centering it in the body part, which is the full
screen without the title bar. This leads to more natural looking
positioning.

components/confirm: improved centering

---

src/ui/components/trinary_input_string.c

The callback was called when the area was tapped even if the cancel
button was not rendered.

components/trinary_input_string: fix cancel

---

src/ui/components/confirm_transaction.c

As the total is a bit more important, it is shown a bit bigger than
the fee.

font-size: smaller font for the fee

---

src/ui/components/confirm_gesture.c

Slightly to the right to make more space for the body.
Straight from #416.

font-size: tweak gesture confirm arrow position

---

messages/backup_commands.options

The fixed_length is used for bytes fields and requires max_size to be
defined as well. BackupListResponse.info doesn't have bytes fields
need not fixed_length. I suspect it might have been a copy&paste typo.
See nanopb docs:
https://jpa.kapsi.fi/nanopb/docs/reference.html#proto-file-options
No changes in the corresponding autogenerated backup pb.h or pb.c
files. Binary size is also the same. Verified backup operations still
work with send_message.py and the desktop app.

protobuf: remove unused fixed_length in backup_commands

---

py/bitbox02/bitbox02/bitbox02/__init__.py

btc_sign() had a breaking change.

py/bitbox02: bump version to 3.0.0

---

.ci/run-container-ci
.github/workflows/ci.yml
.travis.yml
README.md

This is an alternative to Travis CI.
It runs the same scripts in docker on Ubuntu 18.04.

ci: add github workflow

---

.github/workflows/ci.yml

Initial commit 1184760 to set up github CI runners used incorrect
variable to identify the target branch of a pull request for various
style linters.
Here's an example of a failed run:
https://github.com/digitalbitbox/bitbox02-firmware/runs/765310884
This commit hopefully makes it work correctly.
See the following for docs:
https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

ci: make github runner pick correct target branch

---

src/CMakeLists.txt
src/backup.c
src/commander/commander.c
src/commander/protobuf.c
src/commander/protobuf.h
src/restore.c

Easier to call from Rust. (work paused again, but putting in this commit so I don't have to look for it again later).

commander: split protobuf encoding/decoding into new file

---

src/CMakeLists.txt
src/apps/btc/btc_sign.c
src/apps/btc/btc_sign_validate.c
src/apps/btc/btc_sign_validate.h

btc_sign.c is growing too big.
With the next commits we will allow mixed inputs, so the init script
configs validation will be extended.
This commit does not change any semantics yet, just moving code.

apps/btc/sign: move init validation to a new file

---

messages/btc.options
messages/btc.proto
py/bitbox02/bitbox02/bitbox02/bitbox02.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.pyi
py/send_message.py
src/apps/btc/btc_sign.c
src/apps/btc/btc_sign_validate.c
src/apps/btc/btc_sign_validate.h
test/unit-test/test_app_btc_sign_multisig.c
test/unit-test/test_btc_sign.c

Before, one script config (address type) was allowed for all inputs
and changes.
This commit changes the API of the signing workflow to allow
specifying multiple script configurations that can be used in a tx,
instead of only one.
In each output and change, the `script_config_index` now references
which script config to use.
The current commit still only allows only one (see TODO), but
implements the change on the API level. The TODO will be handled in a
subsequent commit.

apps/btc/sign: allow multiple script configs in a tx

---

src/CMakeLists.txt
src/rust/bitbox02-rust-c/src/noise.rs
src/rust/bitbox02-rust/src/hww/noise.rs
src/rust/bitbox02/src/ui.rs

Not doing so is a regression from the rewrite of noise to Rust. This
removes the 'See the BitBoxApp' screen and goes to the default waiting
screen.
See
https://github.com/digitalbitbox/bitbox02-firmware/commit/d90d5e14207fcb1f79a69492c7cee78f71b2ea11#diff-ae8fe1d4fe4e70004f0f0ee3300406e8L189
In the future, we should consider showing the 'See the BitBoxApp'
screen again once the app is closed.
The screen stack pop was moved to the beginning of the handshake as
opposed to the end. This avoids a short flash of the 'See the
BitBoxApp' screen (as there are multiple api calls to finish the
pairing process), and we know the app (or a client) connected when a
handshake request comes in.

noise: pop screens on new handshake

---

src/CMakeLists.txt
src/rust/bitbox02-rust-c/src/bitboxbase.rs
src/rust/bitbox02-rust-c/src/sha2.rs
src/rust/bitbox02-rust-c/src/util.rs

Has false positives that can be very subtle, so best to play it
safe.
https://github.com/async-rs/async-task/issues/23

rust/clippy: disable redundant_clone

---

src/CMakeLists.txt
src/rust/bitbox02-rust-c/src/bitboxbase.rs
src/rust/bitbox02/src/commander.rs
src/rust/bitbox02/src/lib.rs

Easier to pattern match in the future than a bunch of constants.

rust-bindgen: turn commander_error_t into a Rust enum

---

messages/backup_commands.options

The list backup response size. serialized, was up to 33404 bytes if
all fields were maxed out. This is an accident, as we can't even
transmit more than ~7.6k protobuf packets.
In practice, the size was smaller and could not reach those numbers,
because the id field in reality is 64 bytes (format of a 32 byte hash), not up to 256 bytes as specified.
In addition, we reduce the number of max backups in the list of 100 to
50. 50 is still far more than reasonable, but puts the maximum number
of bytes of the response at 7103 bytes.

protobuf/backup: reduce sizes

---

src/CMakeLists.txt
src/rust/bitbox02/src/memory.rs
src/rust/bitbox02/src/ui.rs
src/rust/bitbox02/src/util.rs
src/ui/components/label.c
src/ui/components/label.h

Easiest/first api call to convert to Rust to make it async, so this is
a prerequisite.

rust: bind memory_set_device_name

---

src/apps/btc/btc_common.h
src/apps/btc/btc_sign.c
test/unit-test/test_btc_sign.c

RBF verification is not a security feature (as described in the
comment), but merely a sanity check, meant for advanced wallets like
Electrum.
Locktime on the other hand might be security relevant, when the
referenced block is in the future.
Until now, we verified the locktime if it is enabled anyway, also 0,
as it technically is considered. Practically however, a locktime of 0
has no effect, as the current block is always > 0.
We want to be able to opt-in to RBF with transactions made in the
BitBoxApp. Currently if doing so, the user would be prompted to verify
"Transaction is RBF. Locktime on block: XYZ"
Which is gibberisch to an average user. Especially the latter, a user
can not really verify.
We do a workaround and skip verification of RBF and locktime if the
locktime is zero, with …

apps/btc: do not verify rbf&locktime if locktime is 0

---

Makefile

Without this, "make run-unit-tests" just says "failed" without an explanation of what failed exactly.

unit-tests: print output on failure

---

src/backup/backup.c
src/backup/backup_common.c
src/backup/backup_common.h
test/unit-test/test_backup.c
test/unit-test/test_restore.c

It is sort of an identifer for what created the backup. The way it is
now, the fixture test in test_backup.c will fail when we change the
firmware version. Proiding it explicitly means we can test with any
string in the test.

backup: provide generator to backup_fill

---

messages/backup.proto
src/backup/backup_common.c
test/unit-test/test_backup.c
test/unit-test/test_restore.c

_encode_backup_data() is called manually to calculcate the length of
the serialization of the `data` field. Just passing
`BackupData_fields` is wrong though, as that points to the first field
in the BackupData message, not the `data` field.
Practically the length did not change as serializing the tag for the
first field or the data field resulted in the same length, but it was
very confusing to understand what was going on.
This will help when upgrading nanopb, which changes the fields
representation.

backup: fix call to _encode_backup_data, wrong tag

---

.ci/run-container-ci
Dockerfile
messages/CMakeLists.txt
messages/backup.options
messages/btc.options
src/backup/backup_common.c

Update submodule.
proto3_singular_msgs:true is added. Otherwise, fields that are another
protobuf message, such has Backup.backup_v1, BackupV1.content,
BackupContent.metadata, etc. must manually deal with setting a
corresponding `has_*` field. Converesly, in
BTCScriptConfigWithKeypath.script_config etc., the firmware would need
to validate that `has_script_config = true`, adding code bloat.
To generate the proto files, no global installation of the nanopb
generator is needed. The local one from tools/nanopb is used instead.

nanopb: update to 0.4.1

---

.gitignore
messages/backup.options
messages/backup.proto
messages/backup_commands.options
messages/backup_commands.proto
messages/bitbox02_system.options
messages/bitbox02_system.proto
messages/bitboxbase.options
messages/bitboxbase.proto
messages/btc.options
messages/btc.proto
messages/common.options
messages/common.proto
messages/eth.options
messages/eth.proto
messages/hww.options
messages/hww.proto
messages/keystore.proto
messages/mnemonic.options
messages/mnemonic.proto
messages/perform_attestation.options
messages/perform_attestation.proto
messages/random_number.options
messages/random_number.proto
messages/system.options
messages/system.proto
py/bitbox02/Makefile

- Adds proper namespaces when the proto files are used in other
libraries
- Python hack to insert the package name with `sed` removed
- C names kept the same as before by using
mangle_names:M_STRIP_PACKAGE - avoid super long C struct/enum/define
names.

protobuf: add package name to .proto files

---

src/apps/eth/eth_params.c
src/apps/eth/eth_params.h
test/device-test/src/test_token_pub.c
test/unit-test/test_app_eth_verify.c
test/unit-test/test_ugui.c

Repeating the same field everywhere is inefficient. This change saves
~6kB of binary size after the previous commit added ~51kB of token data.

apps/eth: reduce binary size

---

CMakeLists.txt

Regression fix regarding truncation of large confirmation bodies.

CMakeLists: bump version to 9.1.1

---

.gitignore

This adds some well-known file and dir names which are not typically checked into the repo.

git: ignore C/C++ LSP caches and local configs

---

src/rust/bitbox02-rust/src/hww/api.rs
src/rust/bitbox02-rust/src/hww/api/set_device_name.rs
src/rust/bitbox02-rust/src/hww/api/set_password.rs

Simpler code, simpler to unit test.

rust/hww/api: use Result<> to encode errors

---

src/rust/bitbox02/src/ui.rs
src/rust/bitbox02/src/ui/types.rs

Keep only functions in ui.rs, so it is easier to do a module switch
for testing after.

rust/bitbox02/ui: move types to a new file

---

src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02/Cargo.toml
src/rust/bitbox02/src/lib.rs
src/rust/bitbox02/src/memory_stub.rs

The bitbox02 safely wraps C functions. In Rust tests, C is not linked,
and even if it was, properly mocking the functions would be difficult.
We do a workaround instead: by adding the 'testing' feature and
enabling it only in tests, we can supply stub/mock implementations
that can be used in unit tests, not referencing any C functions.
In future commits, we can add some light mocking infrastructure to be
able to check args and mock the return values.
Alternatives dismissed:
- Add a trait for memory, keystore, ui and mock those.
This resulted in all the code littered with generic params and lots
of boilerplate.
- Implement the C funtions in Rust using cdylib and use that:
Too complicated compared to the testing feature.

rust/bitbox02: add stubs for testing

---

src/apps/common/bip32.c

bip32_key_init() was added some time ago to allow initialising an ext_key without allocating it.

libwally: Avoid working around a quirk that has been fixed in wally

---

src/ui/components/trinary_input_string.c
src/workflow/restore_from_mnemonic.c

When the input is used to enter words from a wordlist (bip39
mnemonic), the title should be rendered at the top instead of at the
center, to be always visible, even when during typing.
- The user usually copies the words from paper, and should never be
disoriented at which word they are.
- This will help with a future change: the user will be able to go
back one word, in which case the previous word will be shown and the
user knows at which position they are.

components/trinary_input: render title on top, always visible

---

src/util.c
src/util.h
src/workflow/confirm_time.c
test/unit-test/test_util.c

Isolate C datetime formatting so it is easier to wrap from Rust.
Rust does not seem to have a good way to format datetimes without the
`chrono` crate, which is huge, also in terms of added binary size.

util: add util_format_datetime

---

src/ui/components/trinary_input_string.c
src/ui/components/trinary_input_string.h
src/workflow/cancel.c
src/workflow/cancel.h
src/workflow/restore_from_mnemonic.c
src/workflow/trinary_input.c
src/workflow/trinary_input.h

It is infuriating to have to restart the whole process and enter again all words in case of mistake. This allows the user to go back and edit the previous word, repeatedly if necessary.
This PR is best looked at commit by commit.

restore from mnemonic: allow editing previous word

---

src/keystore.c
src/keystore.h
src/workflow/show_mnemonic.c
test/unit-test/test_keystore.c
test/unit-test/test_keystore_functional.c

The wally function uses malloc/free. This commit makes this nuisance
internal, so the caller can just use a regular stack var.
This makes it easier to wrap this function in Rust.

keystore: do not require caller of get_bip39_mnemonic to free()

---

src/apps/eth/eth_sign_msg.c
src/rust/bitbox02-rust-c/src/util.rs
src/rust/util/src/ascii.rs
src/rust/util/src/name.rs

Rust's stdlib has a similar method is_ascii but it's different in that
bb's all_ascii considers only printable characters. This commit makes
the distinction explicit.

rust/util/ascii: give all_ascii a more suitable name

---

src/rust/bitbox02/src/lib.rs
src/rust/bitbox02/src/util.rs

There are more than one case where making a C str out of Rust may fail.
For example, when Rust str contains non-ASCII characters.
This commit distinguishes between string length and non-ASCII errors
when panicking.

rust/util: improve errors in str_to_cstr

---

py/send_message.py
src/apps/eth/eth_sign_msg.c
src/rust/Cargo.lock
src/rust/bitbox02-rust-c/src/lib.rs
src/rust/bitbox02-rust-c/src/util.rs
src/rust/bitbox02-rust-c/src/workflow.rs
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/workflow.rs
src/rust/bitbox02-rust/src/workflow/verify_message.rs
src/rust/util/src/ascii.rs
src/rust/util/src/name.rs
test/unit-test/CMakeLists.txt
test/unit-test/test_app_eth_sign_msg.c

Motivation: I saw that Bity makes you sign this kind of message when buying:
```
This message is part of the process of placing an exchange order on bity.com. To proceed, Bity is required to verify that you own the destination crypto address. By signing this message with your wallet, you are confirming 1) that you are the sole owner of the crypto address below and 2) that you will be sending your own funds to Bity. If you did not initiate this process yourself, do not sign this message.
Your order id: 69b87653-.....
Your IBAN: CH1.........
Your crypto address: 36..........
Your crypto address type: BTC
```
The newlines make this show as a hex string. After this PR a message like this can be easily verified.
To test, enter this in send_message for 21) (sign eth msg):
```
This message is …
```

Verify signmsg

---

src/rust/bitbox02-rust/src/hww/api/set_device_name.rs
src/rust/bitbox02/src/memory_stub.rs

This avoids panic on too long strings and non-ascii characters.
The API now responds with ERR_INVALID_INPUT error, as opposed to
ERR_MEMORY in such cases and results in the bb app reporting back with
"Device name could not be set".

rust/api: validate user input in SetDeviceName

---

src/apps/btc/btc_sign_msg.c
test/unit-test/test_app_btc_sign_msg.c

Future script types should not be automatically accepted.
If a future script type had a different signing algorithm, without
this check, and old firmware would just accept the api call and do the
wrong algorithm.

apps/btc/sign_msg: stricter input validation

---

src/rust/bitbox02-rust-c/src/workflow.rs
src/rust/bitbox02-rust/src/hww/api/set_password.rs
src/rust/bitbox02-rust/src/workflow/password.rs
src/rust/bitbox02-rust/src/workflow/unlock.rs
src/rust/bitbox02/src/password.rs

Much better ergonomics and less copies.

rust/password: use heap allocation

---

src/commander/commander_btc.c

It is redundant and possibly confusing, especially since the BitBoxApp
has unified accounts (only one Bitcoin account) by default.

btc: do not show `bech32` in receive screen

---

py/bitbox02/bitbox02/bitbox02/__init__.py
py/bitbox02/bitbox02/bitbox02/bitbox02.py
py/send_message.py
src/rust/bitbox02-rust-c/src/workflow.rs
src/rust/bitbox02-rust/src/hww/api/backup.rs
src/rust/bitbox02-rust/src/hww/api/error.rs
src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs
src/rust/bitbox02-rust/src/workflow/password.rs
src/rust/bitbox02-rust/src/workflow/unlock.rs
src/rust/bitbox02/src/ui/ui.rs
src/rust/bitbox02/src/ui/ui_stub.rs

Builds on #619
When showing mnemonic or creating a backup, the password entry to check the password cannot be aborted. This PR fixes this.

Cancelable password check

---

CMakeLists.txt

Fixes a reproducible builds issue of 9.2.0.

CMakeLists: bump version to 9.2.1

---

src/rust/.cargo/config
src/rust/bitbox02-rust/Cargo.toml

All normal deps are already built from vendored sources.
Prost is a git source. Git sources are vendored with `cargo vendor`,
but not automatically build from the vendored sources with `cargo
build`. The added section in the .cargo/config is needed for that, as
explained by the `cargo vendor` output.
See also: https://github.com/rust-lang/cargo/issues/8792

rust: build prost from vendored sources

---

src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02-rust-c/src/lib.rs

A lot of Rust code is compiled even when the target is the
bootloader. The code is eliminated at link time, but it is better to
not compile it in the first place, for clarity and compile speed.
There is still some unneeded code compiled in util.rs.

rust: compile less code for the bootloader

---

src/rust/bitbox02/src/ui/types.rs
src/rust/bitbox02/src/ui/ui.rs
src/rust/util/src/lib.rs

The title/body buffers are dropped by the end of `to_c_params()`, but
the pointer survived.

rust/bitbox02: fix dangling pointers

---

src/rust/bitbox02-rust/src/bb02_async.rs
src/rust/bitbox02-rust/src/workflow/cancel.rs
src/rust/bitbox02-rust/src/workflow/confirm.rs
src/rust/bitbox02-rust/src/workflow/password.rs
src/rust/bitbox02-rust/src/workflow/sdcard.rs
src/rust/bitbox02-rust/src/workflow/status.rs

Before, the pattern was:
option(&opt).await;
let result = opt.borrow().unwrap()
With unwrap assuming that the option is Some() after the '.await'.
This is unergonomic and has potential for panic. Better:
let result = option(&opt).await;

rust/async: return value directly from the option future

---

CHANGELOG.md
CMakeLists.txt
messages/btc.proto
src/apps/btc/btc.c
src/apps/btc/btc.h
src/rust/bitbox02-rust-c/src/util.rs
src/rust/bitbox02-rust-c/src/workflow.rs
src/rust/bitbox02-rust/src/hww/api/shiftcrypto.bitbox02.rs
src/rust/bitbox02-rust/src/workflow.rs
src/rust/bitbox02-rust/src/workflow/password.rs
src/rust/bitbox02-rust/src/workflow/trinary_input_string.rs

Can test by showing a multisig receive address in send_message, and when prompted for the name, submit the empty string.

Multisig name on device

---

src/apps/btc/btc.c
src/apps/btc/btc_common.c
src/apps/btc/btc_common.h
src/apps/btc/btc_sign_validate.c
test/unit-test/test_app_btc_common.c

The hash is used to identify a multisig registration.
In multisig, the xpub ordering does not really matter, but our hashes
would change with a different order. This was not a real issue in
practice, as Electrum stores and sends the xpubs in the same order
every time.
In PSBT (at least in the way HWI parses it), xpubs are unordered.
This adds a param to the hashing function to sort the xpubs before
hashing, so that their order does not matter.

apps/btc: add param to sort xpubs before hashing

---

src/apps/btc/btc.c
src/apps/btc/btc_common.c
src/apps/btc/btc_common.h
src/apps/btc/btc_sign_validate.c
src/memory/memory.h

Any order of xpubs identifies the same xpub account, and some
downstream projects pass them in in arbitrary order.
When checking for a registered account, we check with both the ordered
and unordered xpubs for backwards compatibility.

apps/btc: use sorted xpubs when registering multisig accounts

---

src/apps/btc/btc.c
src/apps/btc/btc_sign_validate.c
src/apps/btc/confirm_multisig.c
src/apps/btc/confirm_multisig.h
src/rust/bitbox02-rust-c/src/bip32.rs
src/rust/bitbox02-rust-c/src/lib.rs
src/rust/util/src/bip32.rs
src/rust/util/src/lib.rs
test/unit-test/CMakeLists.txt
test/unit-test/test_app_btc_multisig.c
test/unit-test/test_app_btc_sign_multisig.c

Currently we allow only:
m/48'/0'/0'/1' for p2wsh-p2sh
m/48'/0'/0'/2' for p2wsh
Since we only support so few keypaths and script types, we could get
away with skipping verification of them.
We also want to whitelist m/48'/0'/0' for both script types, which is
the keypath used by Nunchuk for any script type. Then it becomes more
important to verify the script type and keypath that is being
registered.

apps/btc/multisig: confirm script type and keypath during registration

---

src/rust/bitbox02-rust/src/apps/bitcoin/keypath.rs
test/unit-test/test_app_btc_common.c

apps/bitcoin: add m/48'/coin'/account' as a valid multisig keypath

---

src/apps/btc/btc.c
test/unit-test/test_app_btc_multisig.c

Previously, multisig keypaths were always 6 elements long:
m/48'/coin'/account'/script'/change/address
Since the introduction of Nunchuk style multisig keypaths:
m/48'/coin'/account'/change/address
They can also be shorter, so the indexing of the change and address
elements was wrong.

apps/btc: fix regression in change/receive elements in multisig

---

py/bitbox02/bitbox02/bitbox02/__init__.py
py/bitbox02/bitbox02/bitbox02/bitbox02.py

Empty account name means the user will be prompted on the device. This
feature is only available since 9.3.0. This patch informs the user to
upgrade if they use this feature, e.g. in HWI.

py/bitbox02: exception for empty multisig acct names on old firmware 

---

CHANGELOG.md
CMakeLists.txt
src/qtouch/qtouch.c

There were occasional non-deterministic device freezes where
processing would stop completely.
Using gdb in semihosting, we saw that it gets stuck in
`qtm_measure_node()`, called from `qtm_samd51_ptc_handler()`.
Making the interrupt call a critical section, making the section
atomic, seems to fix the issue.
It is not 100% clear what was going on, but one theory is that the
interrupt is called while the interrupt is running, stepping on its
own feet. The more USB requests are processed, the more likely a
freeze was, which could mean that the usb requests make the execution
time of the qtouch interrupt longer, increasing the chance of a race
condition.

qtouch: fix device lockup due to a race condition

---

src/apps/btc/btc.c
src/apps/btc/btc_common.c
src/apps/btc/btc_common.h
src/apps/btc/confirm_multisig.c
src/apps/common/bip32.h
src/apps/eth/eth.c
src/keystore.c
src/keystore.h
test/unit-test/CMakeLists.txt
test/unit-test/test_app_btc.c
test/unit-test/test_app_btc_common.c
test/unit-test/test_apps_common_bip32.c
test/unit-test/test_keystore.c
test/unit-test/test_keystore_functional.c

It is about key material (ext_key aka xpub) and is used not only in
BTC, but also in ETH and for computing the electrum encryption key.

keystore: move apps_btc_encode_xpub to keystore

---

.github/workflows/ci.yml
src/apps/btc/btc_sign.c
src/apps/btc/btc_sign_msg.c

To 46da3615b8e0837964f443d6b113ad500ea89f97.
This is a bit ahead of the official latest 0.8.0 release, to include
this commit, which adds secp256k1-zpk as a submodule instead of as a
source-copy inside libwally-core:
https://github.com/ElementsProject/libwally-core/commit/1da463088e64189d04c21073eb8861be1b717ad1
This will make it a lot easier for us use a custom fork of secp256k1,
which we might want to add anti nonce covert channel protection.
The new release also gets rid of all custom commits to libwally-core
and secp256k1, which are now all merged and released upstream.

external: update libwally-core

---

CHANGELOG.md
CMakeLists.txt
src/CMakeLists.txt
src/commander/commander_eth.c
src/rust/Cargo.lock
src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/hww/api.rs
src/rust/bitbox02-rust/src/hww/api/ethereum.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02-sys/wrapper.h
src/rust/bitbox02/Cargo.toml
src/rust/bitbox02/src/app_eth.rs
src/rust/bitbox02/src/keystore_stub.rs
src/rust/bitbox02/src/lib.rs
src/rust/bitbox02/src/testing.rs

the C `app_eth_address()` can be removed once `app_eth_sign_msg()` is ported as well.
This ports retrieving the ETH xpub and showing ETH addresses, including ERC20 tokens.
First two commits are from https://github.com/digitalbitbox/bitbox02-firmware/pull/628, which can be merged soon. It depends on it for `encode_xpub_at_keypath()`.

Rust eth address

---

src/apps/btc/btc.c
test/unit-test/CMakeLists.txt
test/unit-test/test_app_btc.c

More specific function for easier code. Goal: no wally ext_key in the
public api of keystore.

apps/btc: use keystore_secp256k1_pubkey_hash160 instead of get_xpub

---

CHANGELOG.md
src/CMakeLists.txt
src/rust/Cargo.lock
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs
src/rust/bitbox02-sys/wrapper.h
src/rust/bitbox02/src/keystore.rs
src/rust/bitbox02/src/keystore_stub.rs

The function malloc's the word, but the Rust FFI layer assumed it was
a static string. It was functionally correct, as the address was
static, but there was a memory leak due to a missing free().

keystore: fix memory leak in use of keystore_bip39_get_word

---

src/common_main.c

Go into bootloader if there was an error during startup, so a firmware update can be
applied. Otherwise, if there is an Abort() during startup, there would no way to reboot into the
bootloader and the device would be bricked.

common_main: set bootloader auto_enter=true on failures at startup

---

src/common_main.c
src/securechip/securechip.c
src/securechip/securechip.h

Negative values for BB02 generated errors, positive values form
cryptoauthlib generated errors.
`int` is chosen as the result type as an enum type can be coerced into
int8_t, leading to overflow with high ATCA_* values.

securechip: propagate and report error codes

---

src/CMakeLists.txt
src/keystore.c
src/keystore.h
src/keystore/keystore_antiklepto.c
src/keystore/keystore_antiklepto.h
test/unit-test/CMakeLists.txt
test/unit-test/test_keystore.c
test/unit-test/test_keystore_antiklepto.c

Builds on https://github.com/digitalbitbox/bitbox02-firmware/pull/697
Since we have a few places where me make signatures (transactions, msg signing), we make one antiklepto module to reuse the state machine that would have to be replicated everywhere.

Anti-Klepto part 2) add signer nonce commitment functions

---

test/unit-test/test_keystore.c

Zero bytes are also mixed in, but a non-zero value gives more confidence.

unit-test: better host_nonce test in keystore_secp256k1_sign

---

src/CMakeLists.txt

Make cannot know when to rebuild the rust library since it isn't aware
of the source->output dependencies. Cargo does output a "depfile" (which
can be used to teach Make/Ninja about dependencies) but CMake can only
use depfiles if the "Ninja" backend is used.
For now, we add an output that is never produced which will always
trigger a rebuild of the library. Cargo is clever enough to only rebuild
what is needed anyway.

rust: Always reubuild library

---

src/rust/bitbox02-rust/src/workflow/mnemonic.rs

The 24th word is selected from 8 valid candidaes in a menu. The arrows
and the 'select' button are close to each other, so a typo could
happen quite easily. A typo at this stage is very annoying, but also
the user might not even realize it, and they would proceed thinking
they got the right word.

workflow/mnemonic/get: confirm 24th word

---

src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs

Jumping straight to the confirmation workflow can be confusing.

api/show_mnemonic: instruct user to confirm each word

---

src/ui/components/confirm_transaction.c
src/ui/components/confirm_transaction.h
src/workflow/verify_recipient.c
src/workflow/verify_total.c

Make it easier to wrap it Rust.

component/confirm_transaction: simplify callbacks

---

src/rust/bitbox02-rust-c/src/bitboxbase.rs
src/rust/bitbox02-rust-c/src/workflow.rs
src/rust/bitbox02-rust/src/hww/api/backup.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signmsg.rs
src/rust/bitbox02-rust/src/hww/api/error.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02-rust/src/hww/api/reset.rs
src/rust/bitbox02-rust/src/hww/api/set_device_name.rs
src/rust/bitbox02-rust/src/hww/api/set_mnemonic_passphrase_enabled.rs
src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs
src/rust/bitbox02-rust/src/hww/noise.rs
src/rust/bitbox02-rust/src/workflow/cancel.rs
src/rust/bitbox02-rust/src/workflow/confirm.rs
src/rust/bitbox02-rust/src/workflow/mnemonic.rs
src/rust/bitbox02-rust/src/workflow/pairing.rs
src/rust/bitbox02-rust/src/workflow/password.rs
src/rust/bitbox02-rust/src/workflow/unlock.rs
src/rust/bitbox02-rust/src/workflow/verify_message.rs

Easier to propagate errors than checking for a bool.

rust/workflow/confirm: convert to Result return type

---

src/rust/bitbox02-rust/src/apps/bitcoin/util.rs
src/rust/util/src/decimal.rs
src/rust/util/src/lib.rs

This is simpler than modular arithmetic and will also work with
bigints to format Ethereum values, avoiding bigint modular arithmetic.

util: add decimal formatting utility function

---

src/hww.c
src/rust/bitbox02-rust-c/src/async_usb.rs
src/rust/bitbox02-rust/src/async_usb.rs

There are some API workflows that require not only one
request<->response pair, but many request<->resonse pairs in
succession. Bitcoin transaction signing is one such workflow, where
the transaction is streamed in many requests (inputs, outputs,
previous transactions, etc.).
Currently those are all dispatched to individual functions, which
manipulate a global state see what should be processed next. That
sounds exactly what async functions are designed to simplify.
`let usb_in = next_request(usb_out).await;` can be called from any hww
task to wait for another request from the host.
This can turn for example btc signing into a linear async function, in
this style (pseudocode):
```
async fn process_tx(req: Request) -> Response {
for i in 0..req.num_inputs {
let input = …
```

rust/async_usb: add `next_request()` future primitive

---

src/rust/bitbox02-rust/src/hww.rs
src/rust/bitbox02-rust/src/hww/api.rs
src/rust/bitbox02-rust/src/hww/api/error.rs
src/rust/bitbox02-rust/src/hww/noise.rs

Builds on https://github.com/digitalbitbox/bitbox02-firmware/pull/694
Now, in any async api processing function, one can call
`let request = next_request(Response {...}).await?` to wait for
another request from the host.

hww: add `next_request()` future handling noise and protobuf

---

py/bitbox02/bitbox02/bitbox02/__init__.py

Activate the antiklepto protocol in eth_sign(), eth_sign_msg() and btc_sign_msg().

py/bitbox02: bump version to 5.3.0

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs

Confirming the data field without understanding it can be a security
issue. Ideally, all popular contract invocations would be understood
and displayed in a human readable format - showing the raw data is the
last resort. However, the user must understand the meaning when
confirming it.

apps/eth/sign: warn about unrecognized data

---

CHANGELOG.md
py/bitbox02/bitbox02/bitbox02/bitbox02.py
src/keystore.c
src/keystore.h
src/rust/bitbox02-rust/src/hww/api/set_password.rs
src/rust/bitbox02/src/keystore.rs
test/device-test/src/test_backup.c
test/unit-test/CMakeLists.txt
test/unit-test/test_keystore.c

Corresponds to 12 recovery words / 128 bits.

keystore: allow creation of 16 byte seeds

---

CHANGELOG.md
src/memory/memory.h
test/unit-test/test_memory_functional.c

The previous limit of 10 was not enough for a user. While we want keep
as much space reserved for future use as possible, this change should
be okay and still leaves plenty of space. One multisig registration
takes 64 bytes, so we go from 0.625kB to 1.525kB of occupied memory,
out of 8kB in the chunk, with more chunks available for future use.
We can bump the limit easily now since the the space after the multisigs
is unused, so a migration is not necessary.
An alternative to bumping the limit is to provide a way to delete
previous registrations, which would force a re-registration and
re-verification when that multisig account would be used again. This
is also not ideal - having more space to fit accounts is better
and a simpler solution for now. We can observe if there will be users …

memory: increase max number of allowed multisig registrations

---

py/bitbox02/CHANGELOG.md
py/bitbox02/bitbox02/bitbox02/__init__.py
py/bitbox02/bitbox02/bitbox02/bitbox02.py

The use of this offset for uncompressed pubkeys started in Bitcoin,
and in Ethereum, usage is inconsistent.
MyEtherWallet supports both when verifying:
https://github.com/MyEtherWallet/MyEtherWallet/blob/052f697f3b269db4378f331dbb89d24b406bb7c7/src/components/VerifyMessageInput/VerifyMessageInput.vue#L118
Trezor adds this offset as well.
The testing.aopp.group AOPP demo site requires the offset.

py/bitbox02: add offset of 27 when signing an ETH message

---

py/bitbox02/bitbox02/bitbox02/__init__.py

The last tagged and released version is 5.3.0. We accidentally bumped
the major version twice. The next version is going to be 6.0.0.

py/bitbox02: lower version number that was erroneously bumped

---

src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/electrum.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02/src/keystore.rs
src/rust/bitbox02/src/testing.rs

And remove mocking of `keystore_encode_xpub_at_keypath()`, as we can
now call C code from Rust unit tests directly.

rust/bitcoin: unit test xpubs

---

src/sd.c

The out length param defined in f_read is of type UINT (typedef of
unsigned int).
The sd_load_bin function uses size_t for the out length param.
On the BitBox02 they are both 4 bytes so it works out. On x86, size_t
is 8 bytes while unsigned int is only 4 bytes, which leads to a
corrupt value due to the invalid cast.

sd: use right types for length_out

---

src/sd.c

_USE_LFN does not exist - FF_USE_LFN does. This code is not active and
can be removed.
LFN stands for long filename format, an extension to FAT32 that allows
filenames longer than what "8.3 filenames" allow (8 chars + 3 char
extension).
From http://elm-chan.org/fsw/ff/doc/readdir.html:
A short name is automatically generated from a long name according to
the FAT32 spec.
```
When LFN is enabled, a member altname[] is defined in the file
information structure to store the short file name of the object. If
the long file name is not accessible due to a reason listed below,
short file name is stored to the fname[] and the altname[] has a null
string.
```
I assume that in an old version of FatFs, the long filename was stored
in `lfname` and the short name in `fname`, while now the long name is …

sd: remove _USE_LFN sections

---

src/memory/memory.c
test/unit-test/framework/includes/mock_memory.h
test/unit-test/framework/mock_memory.c
test/unit-test/test_memory.c

This will make it easy to mock flash memory and smarteeprom memory
transparently in RAM.

memory: introduce address base to address memory areas

---

CHANGELOG.md
src/keystore.c

Some users test the wallet using these recovery words:
```
abandon abandon abandon abandon abandon abandon abandon abandon
abandon abandon abandon about
```
Which translates to 16 zero bytes. This is a valid seed just like any
other. The BIP39 seed (the stretched seed using the passphrase) which
is used as the root of BIP32 keys is not zero.
Before this patch, users testing with this seed would get BIP39 unlock
errors due to the wrong sanity check.

keystore: allow zero seeds

---

external/CMakeLists.txt
src/rust/bitbox02/src/util.rs
src/ui/components/confirm.c
src/ui/ugui/ugui.c
test/unit-test/test_memory_functional.c

warning: panic message is not a string literal
```
--> ../src/rust/src/util.rs:47:24
|
7 |     Err(msg) => panic!(msg),
|                        ^^^
|
= note: `#[warn(non_fmt_panic)]` on by default
= note: this is no longer accepted in Rust 2021
help: add a "{}" format string to Display the message
|
7 |     Err(msg) => panic!("{}", msg),
|                        ^^^^^
help: or use std::panic::panic_any instead
|
7 |     Err(msg) => std::panic::panic_any(msg),
|                 ^^^^^^^^^^^^^^^^^^^^^^
```
Also, closes https://github.com/digitalbitbox/bitbox02-firmware/issues/799.

tests: fix compile time warnings

---

CMakeLists.txt
Dockerfile
messages/CMakeLists.txt

We installed the Go tool from master, which recently had a change
requiring Go 1.17.
Instead of fixing it, we remove the doc generation from Docker/CMake,
as we don't actively use it.

Docker: remove protoc-gen-doc

---

scripts/format-python

Out of nowhere this exception appears when running `./scripts/docker_exec.sh ./scripts/format-python --check --fast py/`:
```
./scripts/docker_exec.sh ./scripts/format-python --check --fast py/
Traceback (most recent call last):
File "/usr/local/bin/black", line 8, in <module>
sys.exit(patched_main())
File "/usr/local/lib/python3.6/dist-packages/black.py", line 3754, in patched_main
main()
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1034, in main
_verify_python_env()
File "/usr/local/lib/python3.6/dist-packages/click/_unicodefun.py", line 100, in _verify_python_env
raise RuntimeError("\n\n".join(extra))
RuntimeError: Click will abort further execution …
```

scripts/format-python: fix exception related to encodings

---

src/keystore.c
src/keystore.h
test/unit-test/CMakeLists.txt
test/unit-test/test_btc_sign.c
test/unit-test/test_keystore.c
test/unit-test/test_keystore_antiklepto.c

It contains bech32m encoding functionality required for taproot.
anti_klepto was renamed to anti_exfil in
https://github.com/ElementsProject/secp256k1-zkp/commit/e354c5751d670716791778d86c1dcd599f2e1a9c

external: update libwally-core to 0.8.4

---

Makefile

Created by `make run-rust-unit-tests`

Makefile: remove build-build-rust-unit-tests as well

---

external/CMakeLists.txt
src/common_main.c

The libwally dep was upgraded in 98822a3db. There was a breaking
change that the previous commit missed.
https://github.com/ElementsProject/libwally-core/blob/e4b62491b6fcc19f53f4cef4919ec11db62f518d/CHANGES.md#version-082
> struct wally_operations has changed to hold the size of the struct and has an additional member to allow overriding the lib secp context used internally. Users must recompile their applications against this version as a result (re-linking or simply upgrading the shared library is insufficient).
This commit updates this to be compatible with the updated libwally.

wally upgrade fixes

---

Dockerfile

Linting and mypy compatible anymore since a recent Docker image
rebuild installed a newer Python version.
Updating mypy-protobuf also updates the Python protobuf code generator
to fix typing issues.
Black is updated for good measure.
The changes that follow from this (linting fixes, updated protobuf
generated code, etc.) will come in a future commit which will use the
updated Docker image for CI.

Dockerfile: update Python linting, formatting and protobuf tools

---

.ci/run-container-ci
Dockerfile
messages/CMakeLists.txt

Compiling the tool at build time increases build time and complicates
things when we want to support "cargo test" in the rust libraries.

prost: Pre-compile the tool

---

CHANGELOG.md
CMakeLists.txt
messages/cardano.proto
py/bitbox02/bitbox02/communication/generated/cardano_pb2.py
py/bitbox02/bitbox02/communication/generated/cardano_pb2.pyi
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction.rs
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction/cbor.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

Before, ttl=0 was interpreted as "not provided", which means that it
is not serialized and signed.
According to the spec, zero is a valid value for the TTL. It means
however that the transaction can never be mined, as the current slot
will always be bigger than 0.
According to the Adalite team, this type of transaction is used in
meta protocols:
https://github.com/vacuumlabs/adalite/pull/1212#discussion_r755973295
> But TTL = 0 is in theory a semantically valid TTL the transaction
can have - advanced users may leverage that to sign a transaction and
ensure it won't ever be accepted by the blockchain - it's used
e.g. with Ledger when CLI users need to sign separately voting
registration metadata (but the device allows signing only the full tx)
and therefore want to throw away the rest of …

cardano: allow ttl=0

---

CHANGELOG.md
messages/btc.options
messages/btc.proto
py/bitbox02/CHANGELOG.md
py/bitbox02/bitbox02/bitbox02/bitbox02.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.pyi
py/send_message.py
src/apps/btc/btc.c
src/apps/btc/btc_common.c
src/apps/btc/btc_common.h
src/apps/btc/btc_sign.c
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs
test/unit-test/test_app_btc_sign_multisig.c
test/unit-test/test_btc_sign.c

When confirming a tx, the recipient address is reconstructed from the
payload provided in the protobuf `BTCSignOutputRequest` type and
displayed for confirmation.
We previously named the payload `hash` as it always was a hash: either
a pubkey hash in case of P2WPKH (pay to witness pubkey hash), or a
script hash in case of P2SH (pay to scripthash) or P2WSH (pay to
witness script hash).
With the Taproot softfork that recently activated on Bitcoin, the
payload is no longer a hash of something but a 32 byte public key. See
https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki ("Why
is the public key directly included in the output?").
"Payload" as a term is also used in other Bitcoin libraries for the
decoded address input, e.g. in rust-bitcoin. We apply the same rename
to the …

btc: rename output `hash` to `payload`

---

src/bootloader/bootloader.c
src/qtouch/qtouch.c
src/touch/gestures.c
test/unit-test/framework/mock_qtouch.c

Some vars with uint8_t type were actually treated as booleans.
Makes sense to change those to bool so it's easier to read.
Note that this affects qtouch and gestures.
This is a follow up from https://github.com/digitalbitbox/bitbox02-firmware/pull/759#discussion_r653545158.
I haven't actually tried it on a real device yet. Just sending it here so I won't forget.

bootloader: change vars type from uint8_t to bool where makes sense

---

py/bitbox02/bitbox02/communication/generated/cardano_pb2.pyi
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

One proto comment didn't make it in 778bc9ee4, it seems, which added
support for Cardano tokens.

protogen: align source messages with python and rust gen files

---

src/CMakeLists.txt
src/keystore.c
src/keystore.h
src/rust/bitbox02/src/testing.rs
test/unit-test/test_app_btc_common.c
test/unit-test/test_app_btc_multisig.c
test/unit-test/test_app_btc_sign_multisig.c
test/unit-test/test_btc_sign.c
test/unit-test/test_keystore.c
test/unit-test/test_keystore_antiklepto.c

So we can test with seeds of 16 bytes too (12 words), not just 32
bytes (24 words).

keystore: add seed_len to mock_state()

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs

Fixes #843
We previously limited the max. size of contract data to 1024 bytes.
Some smart contract invocations require much larger data,
e.g. transactions involving the Opensea contract. Example tx with a
large data field (~2400 bytes):
https://etherscan.io/tx/0x2db260bf407a246e3bbf57692168238b55b8518ef72c8288e68547e418cf0e08
Ideally, Opensea transactions would be parsed and displayed in a human
readable format instead. The current way to display the raw contract
data is only safe for expert users that know how to verify it, but
that is not feasible for huge contract data fields like with Opensea.
For now, we don't change the data display logic but simply increase
the size limit so transcations with larger data fields don't fail. The
data field is shown in raw hex format, truncated at 320 …

eth/sign: increase size limit for tx data

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/restore.rs

The ID is shown to disambiguate in case there are multiple backups
with the same name.

api/restore: confirm restore and backup name/ID

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction.rs

Token key being: (policy id, asset name).
A duplicate token in an output would be confirmed multiple times by
the user. The resulting tx is valid at the protocol level, but only
the last token with the same key is used when there are duplicates.

cardano/signtx: disallow duplicate token keys in an output

---

external/CMakeLists.txt
src/keystore.c
src/keystore.h
test/unit-test/test_keystore.c

Needed to to generate taproot receive addresses and sign taproot
inputs in transactions.
A taproot output contains a 32 byte x-only pubkey (see BIP-340), which
may or may not be tweaked with the root of a merkle tree containing
execution scripts as leafs.
In a normal single-sig with no extra scripts, BIP-86 specifies:
> BIP 341 states: "If the spending conditions do not require a script
path, the output key should commit to an unspendable script path
instead of having no script path. This can be achieved by computing
the output key point as Q = P + int(hashTapTweak(bytes(P)))G.".
https://github.com/bitcoin/bips/blob/4c6389f8431f677847b115538a47ce8c826c6be8/bip-0086.mediawiki
This commit adds keystore functions to get such tweaked
pubkey (original pubkey tweaked with the hash of the …

keystore: add keystore_secp256k1_schnorr_bip86_[pubkey|sign] funcs

---

src/rust/bitbox02-rust/src/workflow/pairing.rs

Reason: need this function to test the pairing code when unit testing
the noise protocol in a later commit.
We also stop using ArrayString, we are using normal String basically
everywhere else.

pairing: move pairing code formatting to its own function

---

test/unit-test/CMakeLists.txt
test/unit-test/framework/mock_securechip.c
test/unit-test/test_keystore.c
test/unit-test/test_keystore_functional.c

We don't need to mock the input and output of the kdf function in each
unit test - by default it should do the same as the actual securechip,
but with mocked slot contents. This allows unit tests that run
securechip_kdf to work in Rust as well, where we cannot (or will not!)
use cmocka mocking.

unit-test: less manual mocking of securechip_kdf

---

src/rust/bitbox02-noise/src/lib.rs
src/rust/bitbox02-noise/src/noise_xx.rs
src/rust/bitbox02-noise/src/testing.rs
src/rust/bitbox02-rust/src/hww.rs
src/rust/bitbox02/src/ui/ui_stub.rs

We have unit tests for individual API calls, but we didn't have any
the request/response level, including establishing a noise channel.
This can be extended with functional tests, e.g. going through typical
user workflows.

api: add high level unit tests

---

src/CMakeLists.txt
src/bootloader/bootloader.c
src/flags.h
src/memory/memory.c
src/memory/memory_shared.c
src/memory/memory_shared.h
test/unit-test/framework/mock_memory.c

The bootloader and firmware both access the same memory starting at
FLASH_SHARED_DATA_START. The bootloader doesn't link memory.c, and had
a local copy of the relevant struct.
This creates a memory_shared.c linked into both bootloader and
firmware for better code reuse. This is done in preparation of adding
a `screen_type` memory field which will determine which screen driver
to use.

memory: move shared data to new file memory_shared.h

---

src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02-rust-c/src/lib.rs

rust: docs on how to remove eh_personality and build core manually

---

src/rust/bitbox02-rust/src/async_usb.rs
src/rust/bitbox02-rust/src/bb02_async.rs
src/rust/bitbox02-rust/src/hww.rs
src/rust/bitbox02-rust/src/hww/api/backup.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signmsg.rs
src/rust/bitbox02-rust/src/hww/api/cardano/xpubs.rs
src/rust/bitbox02-rust/src/hww/api/electrum.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs
src/rust/bitbox02-rust/src/hww/api/reset.rs
src/rust/bitbox02-rust/src/hww/api/sdcard.rs
src/rust/bitbox02-rust/src/hww/api/set_device_name.rs
src/rust/bitbox02-rust/src/hww/api/set_mnemonic_passphrase_enabled.rs
src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs
src/rust/bitbox02-rust/src/hww/api/system.rs
src/rust/bitbox02-rust/src/lib.rs
src/rust/bitbox02-rust/src/waker_fn.rs
src/rust/bitbox02-rust/src/workflow/menu.rs
src/rust/bitbox02-rust/src/workflow/mnemonic.rs
src/rust/bitbox02-rust/src/workflow/transaction.rs
src/rust/bitbox02-rust/src/workflow/trinary_choice.rs
src/rust/bitbox02-rust/src/workflow/trinary_input_string.rs
src/rust/bitbox02-rust/src/workflow/verify_message.rs

Once in the root lib.rs is enough to make the crate available.

rust: remove unneeded `extern crate ...` statements

---

src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs

A comment was not copied over from C from this commit, when porting
the locktime/rbf checks to Rust:
082dd1ae523fbf868dd178b3e857bf4d15ab70be
The dialog is not shown if locktime is 0, as a beginner user should
not be confrontend with RBF, which is enabled by default in the
BitBoxApp.

bitcoin/signtx: restore comment lost in Rust conversion

---

.ci/run-container-ci
CMakeLists.txt

It would have prevented an issue where reproducible builds failed due
to the version falling back to being 'v0.0.0' instead of exiting with
an error (see e17cfccef30c54cd2646613041b630f823786c87).

cmake: error if get_version fails

---

py/requirements.txt

Added in 9bcae185cc1054bad068d2cc73c56a0d2d2ba063 for the BitBoxBase,
which was removed from the Python libs in
e66818cb2f6a64fce216b7698e8a9443778e27cb. Forgot to remove this dep
here.

py/requirements: remove pyserial

---

.ci/ci
Makefile

Execution of target `run-valgrind-on-unit-tests` looked for tests in the wrong
folder and needed to be wrapped in a single script.

Makefile: fix valgrind execution of unit tests which was broken

---

external/CMakeLists.txt
src/cipher/cipher.c

Before, the submodule pointed to
https://github.com/digitalbitbox/ctaes/tree/cbc, which was a re-host
of https://github.com/bitcoin-core/ctaes/pull/14 before it was merged.
It has since been
merged. https://github.com/digitalbitbox/ctaes/tree/master is now at
8012b062ea4931f10cc2fd2075fddc3782a57ee4, which is up to date with
upstream https://github.com/bitcoin-core/ctaes. The submodule is
updated to this commit revision.

external: update the ctaes dependency

---

.ci/run-container-ci
messages/backup.proto
src/rust/bitbox02-rust/src/lib.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.backups.rs
tools/prost-build/src/main.rs

Make the backup.proto protobuf messages available in Rust, so we can
work with microSD backups in Rust.
The package name of backup.proto is changed as it is 100% independent
of the other .proto files, which all deal with the firmware API. This
results in the different file for the definitions in Rust.
The Docker image is updated because prost-build as modified and it is
pre-compiled during image generation.

prost/protobuf: generate backup.proto for Rust

---

src/CMakeLists.txt
src/apps/btc/btc_sign.c
src/apps/btc/btc_sign.h
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02/src/app_btc.rs

Less reliance on complex C nanopb types, furthering the goal of removing nanopb.

rust/btc: remove an indirection to C

---

py/bitbox02/CHANGELOG.md
py/bitbox02/setup.py

Current py bitbox02 deps require protobuf >= 3.21, which is not compatible
with files generated by protoc < 3.19.
It seems that protobuf v3.20.x is compatible with files generated by
both protoc < 3.19 and >= 3.19. This commit relaxes the constraint to
protobuf version >= 3.20, to provide better compatibility.

py/bitbox02: relax protobuf dependency constraint to v3.20

---

CHANGELOG.md
py/send_message.py
src/commander/commander_states.c
src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs

The normal initialization flow is unseeded -> seeded -> initialized:
SetPassword api call to create the seed and set the password -> seeded.
CreateBackup to create the backup onto a microSD card -> initialized.
ShowMnemonic was only allowed in the initalized state, i.e. after a
microSD card backup was made.
This commit allows skipping microSD card backups in favor of a
mnemonic backup, by allowing the ShowMnemonic API call also in the
seeded (not yet initialized) state.
The api call is modified to set the initialized state, and to not ask
for the user password when not initialized, which is the same way the
CreateBackup call works (which is also allowed after the
initialization).

api: allow ShowMnemonic for initialization (allows skipping SD backup)

---

src/CMakeLists.txt
src/apps/btc/btc_common.c
src/apps/btc/btc_common.h
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02/src/app_btc.rs
test/unit-test/test_app_btc_common.c

This is the last use of nanopb generated code before we can remove the
nanopb dependency. It is only a few enums generated from the protobuf
files. For now, we simply use our own enums instead.

btc/btc_common.h: remove dependency on nanopb header

---

CHANGELOG.md
src/apps/eth/eth_params.c
src/apps/eth/eth_params.h
src/rust/bitbox02-rust/src/hww/api/ethereum/keypath.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02/src/app_eth.rs
test/unit-test/test_ugui.c

This saves 33456 bytes of firmware space.
The full names takes up a lot of firmware space.
The long name is currently only used when displaying a receive address
in the BitBoxApp. In this commit, we use the unit instead of the long
name there.
I added the coin/network name to the title as well, just in case it
becomes helpful (e.g. if we end up having the same token on multiple
EVM chains).

eth/params: remove long name from erc20 tokens

---

README.md

We have not been using Travis in a long time - we only use GitHub
workflows at the moment.

README: remove travis build status

---

src/CMakeLists.txt
src/rust/bitbox02-rust/src/attestation.rs
src/rust/bitbox02/src/lib.rs

Can use the Rust sha256 dep instead.

rust/bitbox02: remove sha256() ffi call

---

src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs

Without a newline, the words touch the cross/checkmarks left and right. The cancel screen after already has a line break in the title, so this makes it also consistent.

show_mnemonic: line break in "Recovery words" title

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/error.rs
src/rust/bitbox02-rust/src/hww/api/restore.rs
src/rust/bitbox02-rust/src/workflow/cancel.rs
src/rust/bitbox02-rust/src/workflow/password.rs
src/rust/bitbox02-rust/src/workflow/trinary_input_string.rs

Before, Generic would be returned no matter if the user did not enter the same password twice or if they aborted on the `Your password has fewer than 4 characters.\nContinue?` screen.
Now that we handle the user abort, we can also allow to abort during password entry itself.

api/setpassword,restore: return UserAbort on user abort

---

src/keystore.c
src/keystore.h
src/rust/bitbox02-rust/src/hww/api/restore.rs
src/rust/bitbox02-rust/src/hww/api/set_password.rs
src/rust/bitbox02/src/keystore.rs
test/unit-test/test_keystore.c
test/unit-test/test_keystore_functional.c

If there was a securechip or memory error, creating or restoring a
wallet would show and return a generic looking error. If e.g. the
securechip is the problem, we want to see that, so the user can better
report the problem.
We might also return a specific error code to the host, but for now
displaying the error will do (same as do when unlocking a device fails).

api: display error type on screen if create/restore fails

---

src/ui/oled/oled.c

This was a rebase error when the OLED code was changed after removing the BitBoxBase.

oled: remove unused #elif clause

---

CHANGELOG.md
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs
src/rust/bitbox02-rust/src/workflow/transaction.rs
src/rust/bitbox02/src/testing.rs
src/rust/bitbox02/src/ui/ui.rs
src/rust/bitbox02/src/ui/ui_stub.rs
src/ui/components/confirm_transaction.c
src/ui/components/confirm_transaction.h

This is to prevent accidents with fees. False positives can happen, but the information might still be useful and the user can confirm the high fee.

bitcoin: warn if fee is higher than 10%

---

releases/build.sh

In 11eea89dffe215461327f8e7a34fbf8cd75ffa07, we updated the base image to Ubuntu 22.04.
`python` is not an installation candidate any longer. We simply remove it, as it was a fix for very old versions, and keep a comment in case someone wants to build these old versoins.
Somehow it seems that `git clone --depth 1` doesn't fetch the tags anymore - fixed by fetching the tags manually.

releases/build.sh: fix to work with recently updated Docker image

---

CHANGELOG.md
src/apps/eth/eth_params.c
src/rust/bitbox02-rust/src/hww/api/ethereum/params.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

Ropsten and Rinkeby ETH testnets are currently deprecated. This commit removes them from the code and introduces support to the Goerly testnet.
Since the erc20 test token has been removed from the wallet-app in 4347b1, it is now removed here too.

eth-testnets: add goerli and remove ropsten and rinkeby

---

src/rust/bitbox02-rust/src/hww/api/backup.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/keypath.rs
src/rust/bitbox02-rust/src/hww/api/restore.rs

If more confirmations/dialogs follow, we use the next arrow.

confirm: use next-arrow instead of checkmark where it makes sense

---

src/keystore.c

Functionally the same, but for clarity it is better to use xpubs where only pubkeys are involved. This will also make it easier to add xpub caching to increase performance if needed (for example, xpubs are derived anew for each BTC transaction input and change).

keystore: use xpubs instead of xprvs where possible

---

test/unit-test/CMakeLists.txt
test/unit-test/test_keystore.c

These unit tests are hard to maintain as there is a lot of mocking with will_return and expect_*. We don't need to mock salt_hash_data and securechip_kdf results, we use existing mock implementations of these that perform the real function (in case of securechip_kdf, the mocked one from mock_securechip.c).

unit-test/keystore: simplify by removing some mocks

---

test/unit-test/test_keystore_antiklepto.c

Don't rely on keystore_secp256k1_pubkey_uncompressed, as this function might disappear when moving it to Rust.

unit-test/antiklepto: different way to get the pubkey

---

src/keystore.c
src/keystore.h
src/rust/bitbox02/src/keystore.rs
test/unit-test/test_keystore.c
test/unit-test/test_keystore_functional.c

Before this commit, we used size_t, uint32_t and uint8_t for seed sizes, which can only be 16, 24 or 32 bytes long.
uint8_t is only needed when storing the encrypted seed length to flash memory (see `memory_set_encrypted_seed_and_hmac()`) and when reading it back. We only keep uint8_t there and use size_t everywhere else for seed lenghts.

keystore: use consistent types for seed length

---

CHANGELOG.md
src/CMakeLists.txt
src/bip32.c
src/bip32.h
src/rust/bitbox02-rust/src/bip32.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/keystore.rs
src/rust/bitbox02-rust/src/lib.rs
src/rust/bitbox02-rust/src/xpubcache.rs
src/rust/bitbox02-sys/wrapper.h
src/rust/bitbox02/src/bip32.rs
src/rust/bitbox02/src/lib.rs

When loading a transaction, every input and change address requires the public key in order to compute the pkScript, which is used in the sighash that is signed.
For single-sig, these public keys are currently always at keypaths:
- `m/(49'|84'|86')/coin'/account'/0/*` (receive inputs)
- `m/(49'|84'|86')/coin'/account'/1/*` (change inputs)
where `coin` and `account` are the same for all inputs/changes in the transaction.
Instead of deriving the xpub at these keypaths repeatedly, we cache the xpubs at the account level and the receive/change level. The xpub then only has to be derived once once for the account level and once for change/receive per script type.
Benefits:
- Greatly increased speed. Loading inputs is now about 3x faster for segwit inputs and around 5x faster for Taproot …

bitcoin/signtx: cache xpubs

---

src/rust/bitbox02-rust/src/hww/api/backup.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/hww/api/rootfingerprint.rs
src/rust/bitbox02-rust/src/keystore.rs
src/rust/bitbox02-rust/src/keystore/ed25519.rs
src/rust/bitbox02/src/input.rs
src/rust/bitbox02/src/keystore.rs
src/rust/bitbox02/src/testing.rs

Same tests as `_test_keystore_get_ed25519_seed()` in `test_keystore.c`. Then we can easily delete
`keystore_get_ed25519_seed()` in C and move it to Rust.

keystore/ed25519: unit test seed generation in Rust

---

Makefile
scripts/container.sh

In cb16b81 and b9a05b1 we added podman support for containers, but `make dockerinit` was still fixed on docker, causing ad error when building and executing a new image with podman installed. This updates the Makefile to use podman if available also when building the image.

scripts/container: add container selection for dockerinit

---

CMakeLists.txt
src/i2c_ecc.c
src/random.c

These symbols are already defined in driver_init.c.
The current GCC version doesn't complain, I discovered this when
trying to build with an updated
GCC (arm-gnu-toolchain-11.3.rel1-x86_64) and getting errors about
these redefinitions.
The reason that the current GCC version (GCC 8) didn't complain and
the updated one (GCC 11) did complain is that the default for the
-fcommon flag changed from on to off in GCC 10.
See:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85678
- https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html (-fcommon)

i2c_ecc,random: remove duplicate definitions

---

messages/eth.proto
py/bitbox02/bitbox02/communication/generated/btc_pb2.pyi
py/bitbox02/bitbox02/communication/generated/eth_pb2.pyi
src/rust/bitbox02-rust/src/hww/api/ethereum/params.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.backups.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

In 8b454550f4961b2d7380885fbd45526d8c5d42bd, Goerli was added, but
accidentally in the generated file, not in the source file. The
generated file is only refreshed if the source files change, which is
why the CI did not catch it.
Since we changed to using chainID instead of ETHCoin in
519a58b17e4692f5d2e6a5793f4c8fc09a312e2c, we remove it again from the
protobuf file.
Similarly, the generated files were not regenerated when updating Prost to
0.11. in 412e3400d627ab0b994df5a92f34c95478535ae5, which adds more
changes to the generated file, like formatting and the
`as_str_name`/`from_str_name` methods.

eth: fix protobuf generated file to remove Goerli

---

src/rust/bitbox02/src/lib.rs
src/rust/bitbox02/src/memory.rs
src/rust/bitbox02/src/ui/types.rs
src/rust/bitbox02/src/ui/ui.rs
src/rust/bitbox02/src/util.rs

Simplify code by using str_to_cstr_vec instead (which we already use in many places for the same purpose), which uses core::alloc::CString for conversion. Since it uses a Vec (heap), one does not have to determine a mac size upfront.
This also saves 4k in binary space, as the macro apparently duplicated a lot of code.

rust: remove str_to_cstr and str_to_cstr_force

---

external/CMakeLists.txt
external/atca_config.h
src/securechip/securechip.c

The library handling the secure chip.
https://github.com/digitalbitbox/cryptoauthlib/tree/v3.2.5
See also:
https://github.com/MicrochipTech/cryptoauthlib/wiki/Upgrading-to-v3.2#api-changes-between-v31x-and-v32x

external: upgrade cryptoauthlib

---

Makefile
test/unit-test/CMakeLists.txt

To build the unit tests without sanitizers, call `make unit-test
SANITIZE=OFF`.
On my machine I can't run sanitizers for some reason, so this is a
workaround. It still defaults to ON, and the CI will keep using the
sanitizers.

Makefile: make unit test SANITIZE_* configurable

---

src/keystore.c

We derived the xprv at keypath twice to mitigate potential bit-flips. Such a bit-flip could be devestating if it happened during computation of an xpub or address returned to the host computer, as funds sent to it could not be recovered.
We plan to encrypt the seed in RAM, involving the securechip, whose use is costly (~100ms per KDF invocation). Since the xprv is needed each input to sign an input in a Bitcoin transaction, computing the xprv twice doubles the time needed to sign an input. There, computing it twice is not needed, as a potential bit flip (which is very unlikely in the first place) would simply result in invalid signatures and a rejected transaction.
The keystore_get_xpub function is still called when accumulating the inputs hash of a BTC transaction (in the first round of …

keystore: derive xprv once not twice when signing

---

py/bitbox02/bitbox02/communication/devices.py

./scripts/lint-python
CI didn't find it earlier as ./scripts/check-pep8 aborts early if there are no Python files in the diff...

py: fix python linter

---

py/bitbox02/CHANGELOG.md
py/bitbox02/setup.py

Fixing https://github.com/trezor/cython-hidapi/issues/151, which includes the fix https://github.com/libusb/hidapi/issues/531, which fixes a bug where on macOS, the interface number of all hid interfaces would be 0. This lead to one BitBox02 multi being listed twice instead of once (as it exposes a second interface for U2F).

py: require hidapi>=0.14.0

---

src/ui/components/button.c

Before the text that was passed to button_create was simply passed as a pointer to the data struct, making it the caller's responsibility to keep the string alive for as long as the component is alive.
The comments in ui.rs were incorrect:
```
bitbox02_sys::trinary_choice_create(
crate::util::str_to_cstr_vec(message).unwrap().as_ptr(), // copied in C
crate::util::str_to_cstr_vec(label_left).unwrap().as_ptr(), // copied in C
crate::util::str_to_cstr_vec(label_middle).unwrap().as_ptr(), // copied in C
crate::util::str_to_cstr_vec(label_right).unwrap().as_ptr(), // copied in C
...
```
Since the three labels are buttons, the text was not copied and the pointer becomes dangling.
I checked all instances and found that all button label strings are
short and fit in 20 bytes. A lower number here …

ui/button: copy text into the button data struct

---

src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/registration.rs

The IsScriptConfigRegistered and RegisterScriptConfig api calls so far are only used for multisig accounts, but they are more general and can be extended to register other types of accounts. We move them to a new file registrations.rs.

bitcoin/multisig: move registration api functions to a new file

---

src/rust/bitbox02/src/keystore.rs

No need to copy that many bytes by having it on the stack.
Also somehow this reduces the binary size by 1472 bytes, which is quite a lot.

keystore: put bip39 word pointers onto heap, not stack

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/keypath.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs

So far we prohibited unusual keypaths (e.g. non bip-44/49/84 keypaths).
When using descriptors/miniscript, there are no specific keypaths to whitelist - the user confirms the keypath at policy registration time. We need to allow exporting the xpub at any keypath so the a descriptor wallet app can construct a policy using BitBox02 xpubs.

api/bitcoin: allow exporting xpub at any keypath with confirmation

---

messages/btc.proto
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/keypath.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/policies.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/registration.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs
src/rust/util/src/bip32.rs

There is a example CLI that works with this PR which:
- creates a miniscript policy
- registers it on the BB02
- generates a receive address
- signs a tx
- verifies that all steps are correct
https://github.com/digitalbitbox/bitbox02-api-go/pull/82
Run with `go run cmd/miniscript/main.go`.
The first commit here is the same as https://github.com/digitalbitbox/bitbox02-firmware/pull/1087

Miniscript: registration & signing

---

src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs

Fixes btc formatting in a policy unit test

bitcoin/policy: fix btc formatting in test

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs

This is especially useful for signing mock transactions on all supported mainnets and testnets on different EVM networks, such as testing WalletConnect integration

eth: allow signing transactions with empty data and 0 value

---

src/rust/Cargo.lock
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/general/screen.rs
src/rust/bitbox02-rust/src/lib.rs

Only used in one case where a heap allocated string will do.

rust/bitbox02-rust: remove arrayvec dep

---

CHANGELOG.md
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs

Outputs of a btc transaction can be marked internal ("ours") or
external.
Before now, internal ones were forced to be change outputs, and the
keypath was validated to be a change keypath.
This commit changes this so that the output can be marked internal and
not be a change output, but a regular output of the same account.
The reason for this change is that some wallets supply the keypath
information to PSBTs even for non-change outputs of the same
account. Until now, e.g. in HWI, we checked if the keypath was
available for an output, and stripped it if it was a change keypath,
so the BitBox02 would not error out. With miniscript, such a check
becomes very difficult, as the change keypath does not need to be on
`/1/*`, but could be anywhere, e.g. in a policy like
`wsh(pk/@0/<10;11>/*))`, …

bitcoin/signtx: allow non-change internal outputs

---

scripts/format

We don't want to format C code found in the the rust vendor folder, which can contain C code (e.g. secp256k1).
Similar to 26dae596763b01b0ed22d15b6231371d320eae10.

scripts/format: exclude rust vendor folder

---

src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/policies.rs

The unit test addresses were verified with an independent miniscript implementation at https://github.com/benma/miniscript-go.

btc/miniscript: activate mainnet, add address unit tests

---

src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02-rust-c/src/util.rs
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/lib.rs

The bitcoin/miniscript deps don't need to be compiled for all targets.
xpubcache was marked as unused in a warning when compiling
factory-setup, so we guard this also by the features only enabled in
the firmware editions.

rust/miniscript: make deps optional, enable by features

---

py/bitbox02/bitbox02/bitbox02/bitbox02.py
py/send_message.py

Some apps use EIP-712 typed messages but provide uints in hex format instead of decimal format.

py/bitbox02: parse eth eip-712 uints as hex

---

.ci/check-tidy
CMakeLists.txt
src/bootloader/bootloader.c
src/memory/memory.c

This change does not modify the resulting images at all, the hashes stay the same. It allows however to use C11 features in future commits, such as static
asserts (https://en.cppreference.com/w/c/language/_Static_assert), which can help improve some compile time checks.

update from C99 to C11

---

Dockerfile

Errored with
```
error: failed to compile `bindgen-cli v0.65.1`, intermediate artifacts can be found at `/tmp/cargo-installmxLBVh`
Caused by:
package `clap_lex v0.5.1` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
Try re-running cargo install with `--locked`
Error: error building at STEP "RUN CARGO_HOME=/opt/cargo cargo install bindgen-cli --version 0.65.1": error while running runtime: exit status 101
```
We do the same fix for cbindgen so that deps don't update unexpectedly.

Dockerfile: fix installation of bindgen-cli

---

releases/build.sh

See the diff for the exact issue that is solved.
The patch is in build.sh so that the documented way (see ./releases/README.md) of reproducing the firmware continues to work. The change is small and well-documented and only applies to v9.15.0, so build.sh continues to be easy to audit.

releases/build.sh: apply patch to fix reproducible build for v9.15.0

---

CHANGELOG.md
src/CMakeLists.txt
src/rust/bitbox02-rust/src/bb02_async.rs
src/rust/bitbox02-rust/src/workflow/cancel.rs
src/rust/bitbox02-rust/src/workflow/confirm.rs
src/rust/bitbox02-rust/src/workflow/menu.rs
src/rust/bitbox02-rust/src/workflow/status.rs
src/rust/bitbox02-rust/src/workflow/transaction.rs
src/rust/bitbox02-rust/src/workflow/trinary_choice.rs
src/rust/bitbox02-sys/wrapper.h
src/rust/bitbox02/src/lib.rs
src/rust/bitbox02/src/screen_saver.rs
src/ui/screen_saver.c
src/ui/screen_saver.h

resolves #856 
First of all, thank you for the dev device!
Tested the receive and send screens with this change, the screen saver doesn't appear there any more.
Since the receive screen uses the `confirm` Component, other confirms have the screen saver disabled as well.
Since I'm far away from C/C++, I'm not sure if the position of the enable / disable are correct there.

disable sceensaver on confirm screens

---

CHANGELOG.md

Accidentally added the screen saver change to 9.15.0

(changelog): move screensaver change to unreleased section

---

messages/btc.proto

These docs make their way into generated code in downstream libs like bitbox-api-rs, where these end up in Rust code interpreted as markdown. `<..>` are then interpreted as illegal/unclosed tags.

messages: add backticks to proto docstring

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/show_mnemonic.rs

When the user wanted to see their recovery words, the only requirement is unlocking the device and then confirming writing down the recovery words. However, because of the scammers around like in Telegram, we wanted to show an additional confirmation screen telling user not to share their recovery words with anyone. Now it is implemented as another step before showing the words and the user has to accept this step also.

show mnemonic: Disclaimer before recovery words

---

CHANGELOG.md
src/rust/bitbox02-rust/src/workflow/mnemonic.rs
src/rust/bitbox02/src/keystore.rs

The function computed all 8 possible 24th candidate words to make up a valid bip39 mnemonic given the first 23 words.
The function is extended to also work with 12 and 18 word mnemonics, returning 128 (resp. 32) possible candidates for the final word.
This function can then be used to make the entry of the final word easier for the 12th/18th word by restricting the keyboard to only allow entering from these candidates. This also allows easily importing seeds that were made without computers by rolling dices or similar, helping with the checksum issue, like we do now for 24 word mnemonics.

workflow/mnemonic: generalize lastword_choices to 12/18/24 words

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs

With support for wallet policies (miniscript), we officially support timelocks, so the comment does not apply anymore.
Furthermore, one warning per input is too much of a UX burden if a user has a transaction with many inputs.

bitcoin: don't warn about "unusual" sequence numbers in tx inputs

---

src/CMakeLists.txt

Apply workaround for a potential miscompilation bug: See
- https://github.com/rust-embedded/cortex-m/discussions/503
- https://github.com/rust-lang/rust/issues/118867 We have not observed any abnormal behavior even though we fulfil all the criteria to be affected (opt-level='z', thumbv7em-none-eabi target, Rust toolchain 1.74.0 being >= 1.73.0), but we apply the workaround just in case.
This increases the binary size of the `make firmware` (Multi) build by 11568 bytes at the time of adding this workaround. This can be removed again once the issue above is fixed and we have updated to a Rust toolchain that contains the fix.
This workaround is one of three suggested alternatives. The other two are:
- Downgrade the Rust toolchain - dismissed as it is harder to do, as it involves re-building …

rust: add workaround for potential compiler bug

---

src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02/Cargo.toml
src/rust/bitbox02/src/lib.rs

The `testing` feature is enabled for *Rust* unit tests, but not for the Rust code when compiled to be linked to the *C* unit tests.
We want to add a simulator in the unit-test directory (as C unit tests are already standalone host binaries that link the full C/Rust firmware code), but need a way to change behavior for the simulator only. The `testing` flag is not enabled there as mentioned above.
We add a `c-unit-testing` feature that is active only in Rust code when linked to the C unit tests (including the simulator) for this purpose.
We wanted to simply enable `testing` there as well, but ran into compilation problems when compiling the Rust unit tests:
```
/usr/bin/ld:
.../build-build-rust-unit-tests/src/../lib/libbitbox_merged.a(bitbox02_rust_c-06ac99f37ae6bb45.bitbox02_rust_c.ff44fdf …
```

rust: add c-unit-testing feature

---

bootloader.ld
firmware.ld
src/flags.h

Document the actual values of the flash partition offsets and update linker scripts to match.

Correct flash memory layouts

---

BUILD.md
CMakeLists.txt
external/CMakeLists.txt
src/CMakeLists.txt

sccache is a binary cache that wraps all calls to gcc/rustc and caches build output in `~/.cache`. This speeds up a build after `make clean` by about 3x. I choose not to put it in the dev dockerfile by default since caching might have unexpected side effects? But I put documentation in the build docs of how to install it.

Add support for optional sccache in build system

---

releases/describe_signed_firmware.py

When this script is called on an unsigned binary, there is a warning
Unrecognized firmware edition
but the script then still parses and dumps information that is completely wrong.
This commit outputs a helpful error message instead and exists.

releases/describe_signed_firmware: add helpful error msg

---

src/rust/bitbox02-rust/src/workflow/confirm.rs
src/rust/bitbox02-rust/src/workflow/status.rs
src/rust/bitbox02-rust/src/workflow/trinary_input_string.rs
src/rust/bitbox02/src/lib.rs
src/rust/bitbox02/src/ui.rs
src/rust/bitbox02/src/ui/ui_stub_c_unit_tests.rs

The `c-unit-testing` is also active in Rust unit tests, so the simulator msgs were printed there. This commit moves the stdout prints to `ui_stub_c_unit_tests.rs`, which is only used in the simulator.

simulator: print simulator msgs only in simulator, not in unit tests

---

src/rust/bitbox02/src/securechip.rs

Same func exists in bitbox02::memory, must have slipped in here by accident.

rust: remove unused function

---

src/bootloader/bootloader.c
src/memory/memory_shared.h

To make it available to the firmware.

bootloader: move boot_data_t to memory_shared.h

---

src/CMakeLists.txt
src/factorysetup.c
src/memory/memory.c
src/memory/memory.h
src/rust/bitbox02-rust/src/attestation.rs
src/rust/bitbox02/src/memory.rs
test/simulator/framework/mock_memory.c
test/unit-test/framework/includes/mock_memory.h
test/unit-test/framework/mock_memory.c
test/unit-test/test_memory.c
test/unit-test/test_memory_functional.c

And use it in the attestation check.
`bootloader_hash_set` is added just in case the memory is unexpectedly not `0xFF` everywhere (the default value for unused/erased memory).

memory: persist attestation bootloader hash

---

py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
py/bitbox02/bitbox02/communication/devices.py
py/send_message.py

For when no USB descriptor is available, where we normally get the info from. We need this now to connect to the simulator with the right params. OP_INFO is available since v5.0.0, and the created after that, so for the simulator this will always work.

py/bitbox02: allow infering version/edition from OP_INFO

---

external/CMakeLists.txt
external/SEGGER_RTT_V796b/Config/SEGGER_RTT_Conf.h
external/SEGGER_RTT_V796b/Examples/Main_RTT_InputEchoApp.c
external/SEGGER_RTT_V796b/Examples/Main_RTT_MenuApp.c
external/SEGGER_RTT_V796b/Examples/Main_RTT_PrintfTest.c
external/SEGGER_RTT_V796b/Examples/Main_RTT_SpeedTestApp.c
external/SEGGER_RTT_V796b/LICENSE.md
external/SEGGER_RTT_V796b/README.md
external/SEGGER_RTT_V796b/RTT/SEGGER_RTT.c
external/SEGGER_RTT_V796b/RTT/SEGGER_RTT.h
external/SEGGER_RTT_V796b/RTT/SEGGER_RTT_ASM_ARMv7M.S
external/SEGGER_RTT_V796b/RTT/SEGGER_RTT_printf.c
external/SEGGER_RTT_V796b/Syscalls/SEGGER_RTT_Syscalls_GCC.c
external/SEGGER_RTT_V796b/Syscalls/SEGGER_RTT_Syscalls_IAR.c
external/SEGGER_RTT_V796b/Syscalls/SEGGER_RTT_Syscalls_KEIL.c
external/SEGGER_RTT_V796b/Syscalls/SEGGER_RTT_Syscalls_SES.c
src/CMakeLists.txt
src/factorysetup.c
src/memory/memory.c
src/memory/memory.h
test/unit-test/test_memory_functional.c

Simplifies the factory setup process by only requiring a Segger JLink device.
We also take the attestation sighash salt from the host for flexibility.

factorysetup: use Segger RTT instead of USB for communications

---

messages/btc.proto
py/bitbox02/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.pyi
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/params.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/payment_request.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

We implement a subset of the payment requests protocol described in SLIP-24: https://github.com/satoshilabs/slips/blob/master/slip-0024.md
Subset means, unlike the full SLIP-24 proposal, this commit does not implement:
- support for multiple outputs per payment request
- support for multiple payment requests per transaction
- memo types other than text memo
- non-empty nonces
The subset is sufficient to cover the first application: selling Bitcoin via PocketBitcoin.
The protobuf messages and code has been designed so that support for the above missing features can be added in a backwards compatible way. This is why there is a `payment_request_index` in the output, which has to be `0` if present, and where at most one output can attach to a payment request.
To allow a payment request to …

bitcoin/signtx: add support for payment requests

---

src/reset.c
src/securechip/securechip.c

secure_chip random function uses atca library for randomness, but this call to library may not be successful and error codes might be returned by atca. In this case, firmware was also calling `Abort()`. This stops the usb connection and terminates the program. Should it happen during a factory reset, then it means the device is left in a half-reset state.
That's why it is a good practice to try this atca library call for randomness multiple times, making it possible to avoid rare unexpected errors from atca random implementation. Furthermore, this commit also specifies a `ATCA_STATUS` code in the abort message, hence allowing debugging a potential error coming from atca.

securechip_random : multiple tries

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/keypath.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/registration.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs

Before, we would restrict the account-level keypaths for multisig to be:
- m/48'/coin'/account'/1' for P2WSH_P2SH
- m/48'/coin'/account'/2' for P2WSH
Since the keypath is verified by the user and the coin network is confirmed for every receive/send, ransom and isolation bypass attacks are mitigated sufficiently, and we can lift this restriction. Note that for wallet policies (of which multisig is a subset of), arbitrary keypaths are already allowed.
When exporting an xpub, we furthermore warned about "unusual" keypaths. In addition to the above keypaths, we also allow exporting the xpub at m/45' without warning, as this path is used by Unchained for their vaults.

bitcoin: allow multisig at arbitrary keypaths

---

CHANGELOG.md
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/keypath.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs

In a BIP-44 keypath `m/purpose/coin/account/{0,1}/addressIdx`, we
disallow addressIdx >= 10000 when verifying receive addresses to
mitigate ransom attacks (attacker as victim verify an address at a
very high index, so the victim cannot find the funds).
The same check is applied to change outputs in transactions for the
same reason.
We also had the same check for inputs in the transaction, but there,
the check is not necessary. We want to be able to spend UTXOs that
were received on high indices.

bitcoin: allow spending UTXOs at very high address indices

---

CHANGELOG.md
src/CMakeLists.txt
src/memory/memory.c
src/memory/memory.h
src/ui/components/info_centered.c
src/ui/components/lockscreen.c
src/ui/components/lockscreen.h
src/workflow/idle_workflow.c

It is useful to see the name of the device before you unlock it. For
example, if you have multiple BitBoxes, it is useful to know which one
is inserted before entering long passwords or passphrases.
The device name is not a secret, and can already be queried in the API
at any time, also before unlock.
Users that dislike this can change the device name in the settings to
something generic.

lockscreen: show device name

---

CHANGELOG.md
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/error.rs
src/rust/bitbox02-rust/src/hww/api/sdcard.rs
src/rust/bitbox02-rust/src/workflow/sdcard.rs
src/rust/bitbox02/src/ui/ui.rs
src/rust/bitbox02/src/ui/ui_stub.rs
src/rust/bitbox02/src/ui/ui_stub_c_unit_tests.rs
src/ui/components/sdcard.c
src/ui/components/sdcard.h

Currently the user has no option to go back from the 'Insert SD Card' screen prompt except by unplugging the device. Maybe the user clicks the button to manage backups in the settings by mistake and they don't have the SD card available and need to cancel the request.
This commit introduces a cancel option on the 'Insert SD Card to continue' screen, allowing going back to the original menu. Thus, unplugging is not needed anymore and the device can continue without an interruption.

sdcard: allow exit from 'Insert SD Card' screen

---

src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs

Since digest-0.13.0, one can convert directly to the `[u8;32]` array.
This does not change the compilation output at all (identical binaries).

rust: use .into not .try_into for hash->array conversion

---

src/rust/bitbox02-rust/src/hww/api/bitcoin/payment_request.rs

pocketbitcoin.com will be able to make payment requests, which will be useful for the Pocket sell feature in the BitBoxApp.

bitcoin: add Pocket pubkey for payment requests

---

src/rust/erc20_params/build.rs

Looping through a HashMap is not deterministic, so the order of the token vars was not deterministic in the generated tokens.rs, breaking deterministic builds. Using BTreeMap instead fixes it, as looping through a BTreeMap happens in key order.

erc20_params: fix deterministic builds

---

py/send_message.py
test/simulator/simulator.c

We might want to use different ports or run multiple simulators in parallel for testing, in which case one must be able to specify the port.

simulator: add `--port` flag

---

test/simulator/simulator.c

One purpose is to be able to track the current simulator version in git history, so when we release it, we know which version it should be.
bitbox02 prefix as we will have simulators for future BitBox versions too.
The firmware version is there so we know which firmware is simulated.
The "simulator<VERSION>" part is to identify the simulator and its version.

simulator: add --version argument

---

CHANGELOG.md
CMakeLists.txt
py/bitbox02/CHANGELOG.md
py/bitbox02/bitbox02/bitbox02/__init__.py
py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
src/hww.c

Write another byte for the initialized status in the _api_info function. This field can be used to check whether a device can be unlocked or not. The unlocked byte is not sufficient because unlocked = false could mean the device is locked or the device is uninitialized.

hww: _api_info write byte for initialized status

---

.ci/ci
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/workflow/transaction.rs

Using this pulls in
`core::fmt::float::float_to_decimal_common_shortest` into the binary,
which is a huge function.
By changing the impl to something simpler, we save 20112 bytes in the binary :O

transaction/fee: don't use fmt with "{.1}" to reduce binary size

---

.ci/run-container-ci
src/rust/rust-toolchain.toml

This reduces the binary size by 3648 bytes.

rust: update toolchain to 1.79.0

---

src/rust/bitbox02-rust/src/workflow/pairing.rs

Good to avoid panics, plus it save some bytes in the binary for code that never executes.

pairing: remove impossible panic

---

external/CMakeLists.txt

Calling autogen.sh instead of autoreconf as autogen.sh also does that
but also calls autogen.sh on secp256k1. Without this change secp256k1
would not build anymore b/c of a build system change in libwally.
USE_BASIC_CONFIG dropped, it's not used anymore in secp256k1.
Darin hack TODO dropped, as libwally's autogen.sh contains it.
Submodule now points to:
https://github.com/BitBoxSwiss/libwally-core/tree/bitbox02-firmware-20240722
which has a custom patch to point its secp256k1 submodule to
https://github.com/BitBoxSwiss/secp256k1-zkp/tree/bitbox02-20240722.

external/libwally-core: update to v1.3.0

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/bitbox02-rust/Cargo.toml
src/rust/bitbox02-rust/src/hww.rs
src/rust/bitbox02-rust/src/lib.rs
src/rust/bitbox02/Cargo.toml
src/rust/bitbox02/src/lib.rs
src/rust/bitbox02/src/testing.rs

We can initialize the vars without it directly.

rust: remove lazy_static dep

---

.github/workflows/ci.yml
.github/workflows/commit-ci.yml
.github/workflows/pr-ci.yml

* Split out Pull Request CI into separate file
* Dispatch one job per commit in PR
I've tested it quite thoroughly on my fork of the repo in github.

ci: Run CI for every commit in PR

---

src/rust/bitbox02-rust/src/hww/api/bitcoin/payment_request.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signmsg.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs
src/rust/bitbox02-rust/src/workflow/verify_message.rs

One screen to introduce the memo, and one screen per line in the
memo. This will allow a nice UX for Pocket to display:
"Memo from POCKET"
"IBAN correct?"
"CH 93 ...."
title_short vs title_long to not change the UX of signmsg while being
able to re-use the same workflow.
Having Pocket add the wording about "IBAN correct?" (or similar) is
a hack/workaround. It would be a better fit to modify SLIP-24 to add a
IBAN memo type, so the BitBox can add specific wording about this. We
don't do this for now to not deviate from the standard, but we might
in the future.

btc/paymentrequest: split memo into multiple screens

---

.ci/check-tidy
.clang-tidy
scripts/tidy

Clangd (C LSP) will run some of the clang-tidy checks if it finds the config in the right place. This gives the developer immediate feedback.

DX: Move clang-tidy config to config file

---

src/rust/bitbox02/build.rs

In this commit the error of missing the cmake build directory is downgraded to a warning. When rust-analyzer and clippy builds the project they will not link the final binary. Therefore it is OK if we are missing the cmake build directory.

rust: Don't panic in build.rs script

---

CHANGELOG.md

Move some items from 9.19.0 that were put there by mistake.
Added an entry for
https://github.com/BitBoxSwiss/bitbox02-firmware/pull/1283.

CHANGELOG: mark 9.20.0

---

.ci/ci
Makefile
test/unit-test/test_memory_functional.c

* In CI all tests failed to run under valgrind since we compiled with ASAN
* The way the tests were run meant that failing tests didn't fail the overall CI job.

ci: Stop if valgrind detects errors

---

CHANGELOG.md
py/bitbox02/CHANGELOG.md
py/bitbox02/bitbox02/bitbox02/bitbox02.py
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/sdcard.rs
src/rust/bitbox02-rust/src/workflow/sdcard.rs
src/rust/bitbox02/src/testing.rs
src/rust/bitbox02/src/ui/ui.rs
src/rust/bitbox02/src/ui/ui_stub.rs
src/rust/bitbox02/src/ui/ui_stub_c_unit_tests.rs
src/ui/components/sdcard.c
src/ui/components/sdcard.h

Check commit messages for detailed explanation.
Let me know if you have a better suggestion for polling interval. You can test and let me know if it takes too long.

Sd auto detect for insert and remove

---

src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02-rust-c/src/util.rs
src/rust/bitbox02-rust/Cargo.toml

For clarity.
The bitcoin dep is now always enabledas it's needed in bip32.rs, which is used not only by the bitcoin app.

rust: add `dep:` prefix when enabling deps

---

CHANGELOG.md
messages/cardano.proto
py/bitbox02/bitbox02/communication/generated/cardano_pb2.py
py/bitbox02/bitbox02/communication/generated/cardano_pb2.pyi
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction.rs
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction/cbor.rs
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction/certificates.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

Allow cardano based on [conway.cddl](https://github.com/IntersectMBO/cardano-ledger/blob/cardano-ledger-conway-1.12.0.0/eras/conway/impl/cddl-files/conway.cddl#L273) to sign messages containing Vote Delegation certificate. This is needed for withdrawing rewards.
I will add tests for firmware soon, just wanted to begin the review process as soon as possible. It has been tested through simulator and works as expected.

cardano: Allow vote delegation

---

src/keystore.c
src/keystore.h
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02/src/keystore.rs
src/rust/streaming-silent-payments/src/lib.rs

A conflicting PR (minitapscript) also does most Taproot tweaking in Rust, deleting the _schnorr_bip86_keypair util function. We can do this here too to avoid relying on that util function in `keystore_secp256k1_get_private_key()`, doing in in Rust instead.

keystore: remove bip86 tweak flag from C, do it in Rust

---

CHANGELOG.md
src/sd.c

This issue was existent for a long time. While using the BitBox02, when the sdcard is plugged into the device and the user unplugs and replugs it, backup operations (e.g., list backups, restore from backup) failed and throwed error from the firmware side.
Sdcard backup operations first check if the sdcard is inserted before calling sdcard interface funtions. This commit fixes the re-insertion problem by reinitializing the sdcard whenever it is checked if it is inserted.
The problem earlier most probably stems from sdcard being in an unexpected state when it is re-inserted. The forced initialization step fixes the broken states.

sdcard: solve backup bug when sd is re-inserted

---

src/keystore.c
src/securechip/securechip.c
src/securechip/securechip.h
test/simulator/framework/mock_securechip.c
test/unit-test/framework/mock_securechip.c

A step towards making the securechip interface generic so other chips can be used instead of ATECC608.

securechip: make securechip_slot_t an internal type

---

.gitmodules
external/CMakeLists.txt
external/mbedtls_config.h
external/optiga_config.h
src/CMakeLists.txt

Needed to interact with the Optiga secure chip.
The optiga-trust-m module was forked to the BitBoxSwiss org, along with its own submodule mbedtls, so we are safe against deps disappearing.

external: add the optiga-trust-m dependency

---

CHANGELOG.md
src/CMakeLists.txt
src/bootloader/startup.c
src/platform/driver_init.c

We don't make use of touch in the production bootloader.

bootloader: qtouch only in devdevice

---

test/simulator/simulator.c

If we don't close the socket we have to wait a couple of minutes until the OS cleans up after us. This is quite annoying because then you can't launch the simulator with the same port immediately after you kill it.

simulator: clean shutdown of socket

---

CHANGELOG.md
CMakeLists.txt
messages/cardano.proto
py/bitbox02/bitbox02/bitbox02/bitbox02.py
py/bitbox02/bitbox02/communication/generated/cardano_pb2.py
py/bitbox02/bitbox02/communication/generated/cardano_pb2.pyi
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction.rs
src/rust/bitbox02-rust/src/hww/api/cardano/sign_transaction/cbor.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

Since the Conway era, the CBOR serialization of inputs and certificates
can optionally be tagged with the 258-tag. This will become mandatory
in a future hardfork.
- https://github.com/IntersectMBO/cardano-ledger/blob/6e2d37cc0f47bd02e89b4ce9f78b59c35c958e96/eras/conway/impl/cddl-files/extra.cddl#L5
- https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml
The protobuf field is named `tag_cbor_sets` to be consistent with
other tooling that names it the same way: https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/4a59d8818402a1d1d4c9939a6a8f606940f51d55/src/types/public.ts#L1874
This change is needed now as some wallets/tools already use this tag,
e.g. delegating to a drep using the https://gov.tools/ DApp.

Cardano: allow serialization using 258-tagged sets

---

scripts/dockerenv.sh

This commit publishes the simulators default port 15423 on the development container so that processes on the host can access it

DX: Publish the simulators port

---

CHANGELOG.md
CMakeLists.txt
py/bitbox02/bitbox02/bitbox02/bootloader.py
py/bitbox02/bitbox02/communication/bitbox_api_protocol.py
py/send_message.py
src/bootloader/bootloader.c

This will allow the bbapp to flash different FW versions, depending on the PCB variants. The initial implementation will respond with a single byte that identifies the Secure Chip: 0 for ATECC, 1 for Optiga.
Note: Based on the changes from #1341

bootloader: add OP_HARDWARE api endpoint

---

Makefile

This simplifies the execution of some jlink scripts available in the scripts/ folder.

Makefile: added targets for  missing jlink scripts

---

src/CMakeLists.txt
src/atecc/atecc.c
src/atecc/atecc.h
src/memory/memory_shared.c
src/memory/memory_shared.h
src/optiga/optiga.c
src/optiga/optiga.h
src/optiga/pal/README.bitbox02.md
src/optiga/pal/README.md
src/optiga/pal/pal.c
src/optiga/pal/pal_gpio.c
src/optiga/pal/pal_i2c.c
src/optiga/pal/pal_ifx_i2c_config.c
src/optiga/pal/pal_logger.c
src/optiga/pal/pal_os_datastore.c
src/optiga/pal/pal_os_event.c
src/optiga/pal/pal_os_lock.c
src/optiga/pal/pal_os_memory.c
src/optiga/pal/pal_os_timer.c
src/rust/Cargo.lock
src/rust/bitbox02-rust-c/Cargo.toml
src/rust/bitbox02-rust-c/src/der.rs
src/rust/bitbox02-rust-c/src/lib.rs
src/rust/bitbox02-rust/src/hww/api/device_info.rs
src/securechip/securechip.c
src/securechip/securechip.h
test/simulator/framework/mock_securechip.c
test/unit-test/framework/mock_securechip.c

This commit implements the securechip.h interface for the Optiga Trust M V3, with an interface and configuration roughly corresponding to how we use the ATECC608 secure chip:
- A KDF key that is internally generated and cannot be read and written from the host MCU
- A KDF key that is generated on the host
- A monotonic counter attached to the first KDF key which limits the maxmium number of uses of the key over the lifetime of the device
- Attestation key that is internally generated and used to sign attestation challenges
The factory setup configures the metadata of each object we use, setting the state to Operational. After this, metadata cannot be changed, and the access conditions apply as specified.
Shielded communication encrypts the communication with the chip and is active and …

securechip: add initial Optiga implementation

---

Makefile
external/CMakeLists.txt

* make should always be called as $(MAKE) in makefiles
* CMake didn't keep job server fds open when explicilty specifying the build command. Starting with CMAKE 3.28 there is a new option to allow for that, but we support much older cmakes than that. (BUILD_JOB_SERVER_AWARE). Not sure when this broke in practice, might have been with some update of Make/CMake or wally. (concurrent builds (-j8) doesn't work right now)

Build: Minor bug fixes

---

CHANGELOG.md
messages/btc.proto
py/bitbox02/CHANGELOG.md
py/bitbox02/bitbox02/bitbox02/__init__.py
py/bitbox02/bitbox02/bitbox02/bitbox02.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.py
py/bitbox02/bitbox02/communication/generated/btc_pb2.pyi
py/bitbox02/bitbox02/communication/generated/cardano_pb2.pyi
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/policies.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/script_configs.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/shiftcrypto.bitbox02.rs

Before, we did this only when sending to the same account. This commit extends this to work when sending to an address of a *different* account of the same keystore.
The bitcoin transaction script_configs field is used for inputs and change outputs. We add a similar list, `output_script_configs`, which allows to attach script configs of different accounts to outputs, with `output_script_config_index` to reference them in the output.
To ensure backwards compatibility, `output_script_config_index` is added as a new field, which takes precedence over
`script_config_index` when set.
The output script configs are validated, but since one can send to any address of the same keystore, the output script config validation allows any combination of script configs, unlike the input script configs. …

bitcoin: display account name when sending to self

---

CHANGELOG.md
py/send_message.py
src/rust/bitbox02-rust/src/hww/api/ethereum/params.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs

add a new screen confirmation to the user verification workflow for known L2s and sidechains

Evm sidechain screen

---

scripts/jlink.gdb

When debugging firmware it is easier to skip the bootloader altogether and go straight to firmware code.
Since VTOR is reset on core reset we need to manually set the PC and SP registers. Issuing a reset will simply try to boot from address 0 again.
If we merge this PR `make run-debug` will always go straight to application code.

debugging: Run firmware without bootloader

---

external/asf4-drivers/hal/utils/include/utils_assert.h

When upgradeing to newer GCC toolchain and newlib this conflict of macro definitions breaks compilation.
More specifically without this I cannot compile on darwin with arm GCC 13 toolchain.

newlib-compat: macro conflict between asf4 and std

---

external/CMakeLists.txt

This enables "ASSERT" macros in asf4 in debug builds, which can find bugs. They will cause a break in execution so you can investigate why the assert was triggered. (this requires GDB to be connected).

asf4: Enable DEBUG and USE_SIMPLE_ASSERT in debug builds

---

src/screen.c

The new ASF drivers changed the behavior of delay_ms. Calling it with 0 seems to mean delay forever and not 0 ms.

screen.c: do not call delay_ms if duration is 0

---

src/optiga/pal/pal_os_event.c

ASF4 timers do not support to register same task twice, so we have to take care and remove it when it was cancelled before it was run.
I ran into an assert in hal with DEBUG enabled
This fixes the assert, but I haven't checked that the optiga still works 100%.

optiga-pal: Fix assert

---

src/rust/bitbox02-rust/src/hww.rs
src/rust/bitbox02-rust/src/hww/api.rs

We had two separate checks to decide if we will allow a protobuf message API call to proceed: in hww.rs (forbid if initialized and locked) and in api.rs in the can_call() function that defines which states the API call can run in.
This makes it a bit hard to follow as split into two locations, and it also prevents us from introducing a protobuf call that is only allowed to run if the device is initialized but still locked. `Unlock` would be such a useful new API call if we want to allow entering the passphrase on the host.
The hww.rs check passed if `!initialized || !locked`, which means the same as `uninitialized || seeded || unlocked`.
We change the `can_call` state checks to include this condition. For this we split the local `Initialized` state into
`InitializedAndLocked` and …

api: centralize state check

---

test/simulator/CMakeLists.txt
test/unit-test/CMakeLists.txt

`.` worked because it's regexp, but not what was meant.

test: fix typo in filename

---

src/rust/bitbox02-rust/src/hww.rs
src/rust/bitbox02-rust/src/hww/api.rs
src/rust/bitbox02-rust/src/hww/noise.rs
src/rust/bitbox02-rust/src/workflow/pairing.rs

Instantiate it in process_packet (for now, later we can push it even to bitbox02-rust-c that calls this function), as e.g. the pairing workflow requires it too.

api: push workflows instance up the stack

---

external/asf4-drivers/hpl/spi/spi_lite.c
external/asf4-drivers/hpl/spi/spi_lite.h
src/CMakeLists.txt
src/memory/spi_mem.c
src/memory/spi_mem.h

This adds an api that allows to easily read/write pages and data buffers, erase sectors or the whole external flash memory.
NOTE: the  code includes a test function to help checking the PR, that will be removed after approval

memory/spi_mem: add spi memory api calls to read/write data

---

src/bootloader/startup.c
src/firmware_main_loop.c
src/u2f/u2f_packet.c
src/u2f/u2f_packet.h
src/usb/class/hid/hid.h
src/usb/class/hid/hww/hid_hww.c
src/usb/class/hid/hww/hid_hww.h
src/usb/class/hid/u2f/hid_u2f.c
src/usb/class/hid/u2f/hid_u2f.h
src/usb/usb_processing.c
src/usb/usb_processing.h
test/simulator/simulator.c
test/unit-test/framework/mock_hidapi.c
test/unit-test/test_simulator.c

It best practice to do as little work as possible in the interrupt handlers. In this commit the parsing is moved from the interrupts handlers to the main loop.
This is also a requirement for having multiple transports.

usb: Move usb handling out into main loop

---

src/keystore.c

In 75cb766d903d48ad76409edf07d85bfde82685d5 it was refactored to be a secure-chip implementation detail.

keystore: remove unused KDF_NUM_ITERATIONS define

---

CHANGELOG.md
src/rust/bitbox02-rust-c/Cargo.toml

Was accidentally not included in the simulator, which is supposed to simulate the Multi edition.

simulator: enable Litecoin

---

src/CMakeLists.txt
src/da14531/da14531_protocol.c
src/memory/memory_spi.c
test/simulator/CMakeLists.txt

If there is no valid firmware UART communication is turned off to avoid spending a lot of cpu cycles trying to boot the da14531.
The firmware version reading function must also fail "gracefully" so that the "device info" endpoint gets some data. If the metadata_version is wrong we return all 0s.

da14531: invalid firmware

---

src/memory/spi_mem.c
src/memory/spi_mem.h
src/platform/platform_init.c
test/simulator/framework/mock_spi_mem.c
test/unit-test/framework/mock_spi_mem.c

This adds api calls to lock/unlock and write a protected area of the memory.
This PR includes a test function to be removed before merging

Spi memory lock

---

src/keystore.c
src/u2f.c
src/usb/usb_processing.c
src/usb/usb_processing.h

The firmware typically expects keep-alive requests every 300ms from the app. However keystore unlock takes about 5-6s so for that single call we reset the watchdog counter to a lower value allowing approximately a 7s gap between messages from the app.
In practice this has worked anyway for the usb stack due to the order of things in the main loop. I.e. check the next incoming message before checking the timeout counter.

usb_processing: increase watchdog timeout once

---

.ci/ci
Makefile
src/bootloader/startup.c
src/rust/bitbox02-rust-c/src/lib.rs

Include debug bootloaders in CI to avoid future breakage

debug: Make plus bootloader buildable

---

src/CMakeLists.txt
src/bootloader/bootloader.c
src/bootloader/startup.c
src/da14531/da14531.c
src/da14531/da14531.h
src/da14531/da14531_handler.c

The user needs the device name to pair
requires ble firmware v3

ble-bootloader: Add device name to default screen

---

src/firmware_main_loop.c

If the bootloader has booted the da14531 chip, we need to send over the current name.

da14531: Send over name on boot

---

src/rust/bitbox02-rust/src/hww/noise.rs

Connecting over Bluetooth requires Bluetooth pairing including pairing code confirmation, so a second noise pairing confirmation is redundant.
This does not prevent the host from requesting a pairing code confirmation on demand anyway at any time, it just does not require confirmation on the device to proceed with communicating over noise, when communicting through the BLE chip.

make noise pairing confirmation optional over BLE

---

src/usb/class/usb_desc_bitbox02plus.h

In the bootloader, we have dedicated targets for bb02 and bb02+, while in the firmware we have one target for both, which lead to this.

usb: fix typo

---

CHANGELOG.md

Touch is removed for BB02, but available for BB02+ to accept the Bluetooth pairing code.

CHANGELOG: bootloader 1.1.0

---

.github/workflows/ci-dev-container.yml
.github/workflows/ci.yml
.github/workflows/pr-ci.yml

There was more stricted default permissions on the upstream repo than I had in the repo where I tested the CI. This change gives the workflow the permission that is needed to publish to GHCR.

ci: Give write permissions to `packages` to workflow

---

src/CMakeLists.txt

The fix for this bug was merged in 1.76 and we use a more recent compiler.
https://github.com/rust-lang/rust/pull/119802

build: Remove workaround for bug in 1.74 and 1.75.

---

src/factorysetup.c

If the BLE boot check failed further below, repeating the factory setup made it report success, as _verify_ble() only checks if the BLE firmware was flashed properly already, and the boot check is skipped in that case.
For now we simply remove this check so every attempt tries the whole BLE setup & verification procedure. To be refactored later.

factorysetup: don't skip BLE if already flashed

---

py/bitbox02/CHANGELOG.md

Plus is/was the product codename, and should not be user-facing.

py/CHANGELOG: rename Plus to Nova

---

src/usb/class/hid/hid.c

The FW was waiting for the "IN" endpoint to be ready when it should've been waiting for the "OUT" endpoint.

usb: Fix timeout bug

---

src/ui/components/confirm.c
src/ui/components/confirm_button.c
src/ui/components/confirm_gesture.c
src/ui/components/confirm_gesture.h

`confirm_gesture_create` was called with `NULL` as parent, so `ui_util_position_right_top(parent, confirm_gesture);` passed NULL, and the function derefed NULL to compute the position.
Though undefined behavior technically, 0 is a valid pointer in the BitBox02 (start of bootloader), so some bytes slightly offset from 0 were used for the positions.
None of that impacted the device behavior though as the positioning of the component was not needed in the first place. The component has a custom _render function that renders the confirm arrows in the right location without looking at `component->position`, so we can just remove the offendling line.
The parent param is removed as it is unused.

fix null ptr deref

---

src/keystore.c
src/keystore.h
src/rust/bitbox02-rust/src/hww/api/bitcoin/signmsg.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/sign_typed_msg.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/signmsg.rs
src/rust/bitbox02/src/keystore.rs
test/unit-test/test_keystore_antiklepto.c

End-goal: reduce the number of secure chip ops when signing a BTC transaction, to reduce the chance of going over the Optiga chip's "rate limit", which induces throttling.
With antiklepto, we derived the private key twice for each input that is signed: once to commit to the nonce, and after that to sign.
This commit decouples the nonce commit and sign functions from the underlying keystore, and allows reusing a private key instead of re-deriving it, which requires secure chip operations.
This halves the number of secure chip ops needed per input when signing a BTC transaction.
We do not reuse the privkey for the other instances of antiklepto (signing a msg, signing an ETH tx), as there it's one commit/sign pair only and unlikely to cause secure chip throttling.

keystore: pass private key to nonce_commit() and sign()

---

src/rust/bitbox02-rust/src/bip32.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/common.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/multisig.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/policies.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/script_configs.rs
src/rust/bitbox02-rust/src/hww/api/bitcoin/signtx.rs
src/rust/bitbox02-rust/src/hww/api/electrum.rs
src/rust/bitbox02-rust/src/hww/api/ethereum/pubrequest.rs
src/rust/bitbox02-rust/src/keystore.rs
src/rust/bitbox02-rust/src/xpubcache.rs

End-goal: reduce the number of secure chip ops when signing a BTC transaction, to reduce the chance of going over the Optiga chip's "rate limit", which induces throttling.
By default keystore::get_xpub computed the xpub twice, to mitigate potential bitflips, which could be bad when delivering the wrong xpub (or derivatives) to the host.
When signing a transaction however, one does not need the extra protection - if there is a bit flip, the resulting signature will be invalid.
This commit reduces the number of secure chip ops needed when the bitflip mitigation is not required.
The existing method `get_xpub` was renamed so the compiler can tell us all the instances where we need to decide between one or the other.

xpubcache: allow choosing if xpub computation should be repeated

---

CHANGELOG.md
src/rust/bitbox02-rust/src/workflow/mnemonic.rs

`1 of 24`, `2 of 24`, ... instead of `1st word`, `2nd word`, ...
This is to be more explicit about the number of words being restored.

ui: change title to include number of words

---

src/rust/bitbox02-rust/src/hww/api/set_password.rs
src/rust/bitbox02-rust/src/keystore.rs
src/rust/bitbox02-sys/build.rs
src/rust/bitbox02/src/keystore.rs
src/rust/bitbox02/src/securechip.rs
src/securechip/securechip.h
test/hardware-fakes/src/fake_securechip.c

We count the number of security events the securechip functions take, and then assert in the keystore unit tests how many events the functions take there.
This is a basis for trying to reduce the count, so we can measure the changes properly. Too many events induce throttling.

securechip: count optiga security events and integrate into tests

---

src/hardfault.c

If testing code calls abort, print the error message to stderr and exit the process.

hardfault: Make Abort more useful when developing

---

src/keystore.c
src/keystore.h
src/rust/bitbox02-rust/src/bip39.rs
src/rust/bitbox02-rust/src/keystore.rs
src/rust/bitbox02-rust/src/lib.rs
src/rust/bitbox02/src/keystore.rs
src/rust/util/src/cell.rs
src/rust/util/src/lib.rs

The root fingerprint API call, calling
`bitbox02_rust::keystore::root_fingerprint()`, used two securechip
operations. Using too many operations too quickly in Optiga leads to
throttling, and the BitBoxApp fetches the root fingerprint every time
the BitBox is unlocked.
We can get away with not using hte securechip at all to get the root
fingerprint, by computing and storing it during unlock.
The global static mut could have lived in keystore.c with the other
static muts there, but adding more C code and Rust wrappers seemed
wrong. For now it lives in bitbox02::keystore, and would move over to
bitbox02_rust::keystore when the unlocking functions are migrated to Rust.

keystore: reduce secure chip operations by precomputing fingerprint

---

CHANGELOG.md
test/hardware-fakes/src/fake_memory.c

Disclaimer: This is a mixture of educated guesses, AI, and the little C I remember writing 15 years ago... so please keep that in mind while reviewing :D Anyway I tested it manually and it seems to work fine. 
If the env variable FAKE_MEMORY_FILEPATH is provided, the simulator will
write to file using three different files:
- ${FAKE_MEMORY_FILEPATH}_shared
- ${FAKE_MEMORY_FILEPATH}_app
- ${FAKE_MEMORY_FILEPATH}_smarteeprom
mimicking the behaviour used when reading/writing to memory.

test: add option for the simulator to write to file.

---

CHANGELOG.md
CMakeLists.txt
src/sd.c

When the sdcard is inserted, the sdcard check runs into the retry loop. In that case, the clock was not paused, which could lead to touch issues.

sd.c: always pause clock after sdcard check

---

src/rust/bitbox02-rust/src/workflow.rs
src/rust/bitbox02-rust/src/workflow/mnemonic.rs
src/rust/bitbox02-rust/src/workflow/mnemonic_c_unit_tests.rs
src/rust/bitbox02-rust/src/workflow/testing.rs

`show_and_confirm_mnemonic(hal: ...)` did not use the HAL for all UI: show_mnemonic and confirm_mnemonic directly used the BitBox02 menu workflow without going through HAL. Can't use `hal().ui().menu(...)`, becaus:
- these functions bolt a cancel prompt on top
- show_mnemonic is not a normal menu where one can pick an entry, it's just a scroll-through for displaying the mnemonic
This should make it possible to mock/fake/test the mnemonic workflow functions, and provide different implementations for them in future BitBox hardware.

workflows: use HAL for showing mnemonic and mnemonic quiz
